### ISSUE TITLE
termite plot squished

### ISSUE THREAD

**Issue by rxng** [chartbeat-labs/textacy#102]
When generating the termite plot and setting figure.autolayout to true,  the plot always appears as such .. is there a way to actually just generate the plot at default ratio dimensions?
<img width="207" alt="image copied on 2017-05-14 at 11 24 am" src="https://cloud.githubusercontent.com/assets/19649766/26031028/1e8bdf80-3898-11e7-810f-077c42e3a165.png">

**Comment by bdewilde** [comment]
Hi @rxng, Could you provide a code example to reproduce this? What happens if you _don't_ set `figure.autolayout` to True? And what are your OS and package versions?

**Comment by rxng** [comment]
Hi @bdewilde 

This happens 
<img width="291" alt="image copied on 2017-05-14 at 16 09 pm" src="https://cloud.githubusercontent.com/assets/19649766/26032191/c43261f8-38bf-11e7-9252-95f4782dfb43.png">

with this code ( I have hosting it as a wsgi script). My normal bar charts work, just the termite one doesn't

   ```
 import matplotlib
    import matplotlib.pyplot as plt
    from matplotlib import rcParams
        data[0].termite_plot(data[1], data[2], topics=-1, n_terms=25, sort_terms_by='seriation', highlight_topics=range(0,6))

        sio = cStringIO.StringIO()
        plt.savefig(sio, format='png')

        return """<img class='headbar' src="data:image/png;base64,{0}"/>""".format(sio.getvalue().encode("base64").strip())
```

**Comment by rxng** [comment]
@bdewilde 
I identified that it only happens when number of topics is low

**Comment by bdewilde** [comment]
Hi @rxng , I can't reproduce your error within textacy: termite plots are correctly displayed, even with very few topics. That said, I also wasn't able to generate a figure from the last line of your code snippet, which is almost certainly where the problem occurs... I don't know what I can do to help debug this problem.

**Comment by bdewilde** [comment]
Scratch that, I _did_ get the HTML generated by that last line to work, and I _do_ see the cut-off terms. I still have no idea how to debug; seems like a problem with matplotlib and/or HTML, no?

**Comment by bdewilde** [comment]
UGH, I should stop posting too soon. I found a trivial solution: Try replacing `plt.savefig(sio, format='png')` with `plt.savefig(sio, format='png', bbox_inches='tight')`. The resulting imgs were un-clipped.
