### ISSUE TITLE
cannot import textacy in pycharm python console from remote host

### ISSUE THREAD

**Issue by jkgenser** [chartbeat-labs/textacy#104]
When I try to load textacy in my python console in PyCharm, connected to a remote host, it throws an error. 

I can load spacy fine, but when `import textacy` runs, it throws an error about Qt5Agg interactive backend. 

## Expected Behavior

I expect the import to load without throwing an error. 

## Current Behavior

Note, I am using a conda environment. 

```
Backend Qt5Agg is interactive backend. Turning interactive mode on.
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
Available platform plugins are: minimal, offscreen, xcb.
Reinstalling the application may fix this problem.
bash: line 1: 13805 Aborted                 env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/home/jgenser/Projects/text:C:/Users/jgenser/Projects/analytics:/home/jgenser/.pycharm_helpers/pydev" "PYCHARM_HOSTED"="1" "IPYTHONENABLE"="True" "PYTHONDONTWRITEBYTECODE"="1" "JETBRAINS_REMOTE_RUN"="1" "PYTHONIOENCODING"="UTF-8" /home/jgenser/anaconda2/envs/nlp/bin/python2.7 /home/jgenser/.pycharm_helpers/pydev/pydevconsole.py 0 0
```

This is only an issue with interactive runtime. However, in order to debug my programs, I need to be able to access the pycharm interactive mode. 

For example, the following code runs fine when invoked from the command line. The process just prints `done` and closes. 

```
import spacy
import textacy


if __name__ == '__main__':
    print 'done'
```

## Steps to Reproduce (for bugs)

1.
1.
1.

## Your Environment

* `textacy` and `spacy` versions: textacy version 0.3.4, spacy version 1.8.2
* Python version: 2.7.13
* Operating system and version: RHEL: 3.10.0-514.10.2.el7.x86_64

**Comment by bdewilde** [comment]
Hi @jkgenser , I don't use PyCharm or conda, so this isn't something I can readily reproduce. I also don't know what you mean by "connected to a remote host", or how that would affect imports.

At first glance, it looks like a `matplotlib` error (along the lines of [this](https://stackoverflow.com/questions/28646167/pycharm-wont-open-matplotlib-plots-correctly), maybe?). Could you try re-installing `matplotlib`? Does this work if you aren't connected to a remote host? Just trying to isolate the error...

**Comment by jkgenser** [comment]
@bdewilde Thank you for the reponse. I figured it out.

**Comment by bdewilde** [comment]
Hey @jkgenser , just out of curiosity: What was the problem?

**Comment by jkgenser** [comment]
@bdewilde thanks for getting back to me. I think it was an error with my pycharm and the pyqt package. I updated my pycharm client and it has been working fine for me thus far.
