### ISSUE TITLE
IndexError in terms_to_semantic_network, need to check for empty term list

### ISSUE THREAD

**Issue by ardeego** [chartbeat-labs/textacy#105]
Need to check for empty term list in terms_to_semantic_network()
[network.py#L69](https://github.com/chartbeat-labs/textacy/blob/master/textacy/network.py#L69)

## Expected Behavior
Should not try to build graph on an empty term list

## Current Behavior
Does not check for empty term list before indexing

## Possible Solution
Check for empty list and return None?, or don't try to build network if the term list has been pruned to zero length

## Steps to Reproduce (for bugs)
set terms = [] in argument list

## Your Environment
{'platform': 'darwin',
 'python': '3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12) \n[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]',
 'spacy': '1.8.2',
 'spacy_models': ['en', 'en_core_web_md'],
 'textacy': '0.3.4'}

**Comment by bdewilde** [comment]
Thanks for the heads-up! This has been fixed in master.
