### ISSUE TITLE
Warning: no model found for 'en'

### ISSUE THREAD

**Issue by chrisspen** [chartbeat-labs/textacy#107]
I installed textacy following the [instructions in the docs](http://textacy.readthedocs.io/en/latest/index.html). However, when I try to load a document from a raw string, again, like [outlined in the docs](http://textacy.readthedocs.io/en/latest/api_reference.html#module-textacy.doc), I get the warning:

    Warning: no model found for 'en'

    Only loading the 'en' tokenizer.

How do I load this model and fix this warning?

**Comment by bdewilde** [comment]
Hi @chrisspen , you're probably instantiating a `textacy.Doc` using an English-language text, whose language is automatically detected as "en". `textacy` then attempts to load the corresponding spaCy model. If you've downloaded, say, the `en_core_web_sm` spaCy model and have not aliased it to `en`, then `spacy` doesn't know which model you want to use and falls back on a generic English-language tokenizer without models loaded.

You can do a couple things to solve this problem:

1. Alias a more specifically named spaCy English model to "en". See [here](https://spacy.io/docs/usage/models#usage).
2. Instantiate the `textacy.Doc` with an already-loaded spaCy model you want to apply, e.g. `textacy.Doc(my_text, lang=my_spacy_model)`, or with the model name, e.g. `textacy.Doc(my_text, lang="en_core_web_sm")`.

Model naming, downloading, and loading in `spacy` changed relatively recently, and I've resisted the urge to automatically guess for users which model they actually want until I see what spaCy's v2 looks like.

**Comment by Wapiti08** [comment]
```              
  spacy_lang = textacy.load_spacy_lang("en_core_web_en")
  docx_textacy = spacy_lang(sentence)
```
