### ISSUE TITLE
enhancement for LDA models

### ISSUE THREAD

**Issue by jkgenser** [chartbeat-labs/textacy#108]
textacy currently supports `lda`, `nmf`, and `lsi `models built on sklearn classes. Among the 3, `lda` has a n_jobs parameter that allows you to parallelize the fitting of the model. 

I would love for this to be added to the `textacy.tm` API so that I can specify n_jobs rather than having it default to 1. 

The way that I'm currently doing it is to pass in a [sklearn.decomposition.LatentDirichletAllocation](http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html) class. However the issue is that sklearn implementation obviously does not have the nice methods on `textacy.tm` models like `top_topic_docs`, `top_topic_terms`, etc.

**Comment by bdewilde** [comment]
Hi @jkgenser , sorry about the belated response. You should be able to pass in an `n_jobs` param when instantiating the `TopicModel` class — see [here](https://github.com/chartbeat-labs/textacy/blob/master/textacy/tm/topic_model.py#L126). Does `textacy.tm.TopicModel('lda', n_jobs=2)` not work for you?

**Comment by jkgenser** [comment]
It works and makes complete sense. Thank you! Sorry for missing something so obvious.
