### ISSUE TITLE
Warning:  textacy is not able to load files written in python 3.5 from 3.6

### ISSUE THREAD

**Issue by gryBox** [chartbeat-labs/textacy#114]
Recently I upgraded to python 3.6 from 3.5 in Windows 7.  When I tried loading textacy docs encoding errors ensued.   I re-saved the contents writing with python 3.6 and read them back successfully.  The problem seemed to come from spacy ... . 

Obviously this issue is deep in the stack - And thus only a warning

**Comment by bdewilde** [comment]
Hey @gryBox , thanks for the heads-up. Could you provide a full code snippet to demonstrate the problem? I'm happy to take a look...
