### ISSUE TITLE
Error while importing textacy on virtualenv. I am using macosx and python installed in virtualenv.

### ISSUE THREAD

**Issue by iporky** [chartbeat-labs/textacy#122]
Traceback (most recent call last):
  File "data/test3.py", line 23, in <module>
    import textacy
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/textacy/__init__.py", line 20, in <module>
    from textacy import tm
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/textacy/tm/__init__.py", line 1, in <module>
    from .topic_model import TopicModel
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/textacy/tm/topic_model.py", line 10, in <module>
    from textacy import viz
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/textacy/viz/__init__.py", line 1, in <module>
    from .network import draw_semantic_network
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/textacy/viz/network.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/shivangchauhan/spaCy/.env/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 19, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
(.env) 1178320-C02SL53UG8WN:spacy shivangchauhan$ brew install python --framework

**Comment by bdewilde** [comment]
Hi @iporky , that looks to be an issue with your `matplotlib` installation. Could you try uninstalling then re-installing it within the virtualenv? Also, could you give a full code example that I could use to try and replicate the error?

**Comment by iporky** [comment]
hi thanks for the early reply, i imported like this:

from __future__ import absolute_import, division, print_function, unicode_literals

def read_file(file_name):
    with open(file_name, 'r') as file:
        return file.read().decode('utf-8')


from spacy.matcher import Matcher
from spacy.attrs import ORTH, TAG, LOWER, IS_ALPHA, FLAG63
import spacy


from collections import defaultdict
from itertools import takewhile
from operator import itemgetter
import re

from cytoolz import itertoolz
from numpy import nanmin, nanmax, zeros, NaN
from spacy.parts_of_speech import CONJ, DET, NOUN, VERB
from spacy.tokens.span import Span as SpacySpan

import textacy
from textacy import spacy_utils, text_utils
from textacy.compat import unicode_
from textacy.spacy_utils import (normalized_str, get_main_verbs_of_sent,
                                 get_subjects_of_verb, get_objects_of_verb,
                                 get_span_for_compound_noun,
                                 get_span_for_verb_auxiliaries)
from textacy.constants import NUMERIC_NE_TYPES, REPORTING_VERBS

nlp = spacy.load('en')

text = read_file('data/test2.txt')
processed_text = nlp(text)

**Comment by iporky** [comment]
i also installed textacy in virtaul env like this:
pip install textacy[all]

**Comment by bdewilde** [comment]
Okay. Can you import `matplotlib` separately in this env? Did un- then re-installing the library help?

**Comment by iporky** [comment]
ihi sorry , i am noob in python and pip :( Could you tell me how do i uninstall matplotlib ?

**Comment by phillbaker** [comment]
For other folks that end up here this issue was helpful: https://github.com/JuliaPy/PyCall.jl/issues/122

for pyenv folks:

```
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.4.3
```
