### ISSUE TITLE
Error while running text_stream, metadata_stream = textacy.fileio.split_record_fields(records, 'text')

### ISSUE THREAD

**Issue by davidcomfort** [chartbeat-labs/textacy#123]
Error while running example command 
>>> text_stream, metadata_stream = textacy.fileio.split_record_fields(records, 'text')

####
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-4-c9960789346b> in <module>()
----> 1 text_stream, metadata_stream = textacy.fileio.split_record_fields(records, 'text')

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/fileio/utils.pyc in split_record_fields(items, content_field, itemwise)
    152         return ((item.pop(content_field), item) for item in items)
    153     else:
--> 154         return unzip(((item.pop(content_field), item) for item in items))
    155 
    156 

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/fileio/utils.pyc in unzip(seq)
    163     # check how many iterators we need
    164     try:
--> 165         first = tuple(next(seq))
    166     except StopIteration:
    167         return tuple()

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/fileio/utils.pyc in <genexpr>(***failed resolving arguments***)
    152         return ((item.pop(content_field), item) for item in items)
    153     else:
--> 154         return unzip(((item.pop(content_field), item) for item in items))
    155 
    156 

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/datasets/capitol_words.pyc in records(self, speaker_name, speaker_party, chamber, congress, date_range, min_len, limit)
    232             False, speaker_name, speaker_party, chamber, congress, date_range,
    233             min_len, limit)
--> 234         for record in records:
    235             yield record
    236 

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/datasets/capitol_words.pyc in _iterate(self, text_only, speaker_name, speaker_party, chamber, congress, date_range, min_len, limit)
    242         """
    243         if not self.filename:
--> 244             raise IOError('{} file not found'.format(self._filename))
    245 
    246         if speaker_name:

IOError: /Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/data/capitol_words/capitol-words-py2.json.gz file not found

## Your Environment

{'platform': 'darwin',
 'python': '2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]',
 'spacy': '1.9.0',
 'spacy_models': ['en'],
 'textacy': '0.4.1'}

**Comment by harryhoch** [comment]
@davidcomfort, you are running the example in the README.md, right? 

try 
cw = textacy.datasets.CapitolWords()
cw.download() 

before getting the records and doing the split
the cw.download() call grabs the data and installs it locally. 

Will submit a PR with a change to the README

**Comment by davidcomfort** [comment]
Yes, running the examples in the README.md.

I ran the above and got no error, but I did get an error when I ran the next statement:
corpus = textacy.Corpus('en', texts=text_stream, metadatas=metadata_stream)

***************
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-4cf767098cf9> in <module>()
----> 1 corpus = textacy.Corpus('en', texts=text_stream, metadatas=metadata_stream)

/Users/dcomfort/anaconda/envs/py27/lib/python2.7/site-packages/textacy/corpus.pyc in __init__(self, lang, texts, docs, metadatas)
    140             msg = '`lang` must be {}, not "{}"'.format(
    141                 {unicode_, SpacyLang}, type(lang))
--> 142             raise ValueError(msg)
    143         self.spacy_vocab = self.spacy_lang.vocab
    144         self.spacy_stringstore = self.spacy_vocab.strings

ValueError: `lang` must be set([<type 'unicode'>, <class 'spacy.language.Language'>]), not "<type 'str'>"

**Comment by bdewilde** [comment]
Thanks to @harryhoch for the PR — it's an easy fix, and I'll get that merged in soon. As for @davidcomfort 's last error, the message is clear: `textacy` expects either unicode or an initialized `spacy` language object, not bytes. The easiest fix would be to do `corpus = textacy.Corpus(u'en', texts=text_stream, metadatas=metadata_stream)`, or at the top of the code, add `from __future__ import unicode_literals`.
