### ISSUE TITLE
You can't perform that action at this time and can't fork

### ISSUE THREAD

**Issue by laugustyniak** [chartbeat-labs/textacy#130]
I can't either start the repository or fork it. I got error during starring repo

> You can't perform that action at this time. 

and infinite loading when I tried to fork it. 

Does anybody have similar problems?

**Comment by bdewilde** [comment]
Hey @laugustyniak , sorry I missed this. Github had a brief outage on Friday — maybe that's related? Have you tried this again? I just now successfully "starred" this repo.

**Comment by laugustyniak** [comment]
I solved it, the problem was uBlock Origin plugin in Chrome. I disabled the plugin and all works again.
