### ISSUE TITLE
Textacy with Jupiter

### ISSUE THREAD

**Issue by ajakupov** [chartbeat-labs/textacy#133]
Hello,

I'm trying to install textacy on Jupiter Notebook but the notebook keeps sending me the same error message "PermissionError: [Errno 1] Operation not permitted".
How do I handle this issue. I'm using Python 3 Notebook. To install textacy I type the following command:
!pip install textacy.

Thank you in advance

**Comment by ajakupov** [comment]
`Installing collected packages: cytoolz, pyphen, regex, dill, ujson, pathlib, plac, termcolor, thinc, spacy, unidecode, python-levenshtein, textacy
  Found existing installation: cytoolz 0.7.3
    DEPRECATION: Uninstalling a distutils installed project (cytoolz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling cytoolz-0.7.3:
      Successfully uninstalled cytoolz-0.7.3
  Rolling back uninstall of cytoolz
Exception:
Traceback (most recent call last):
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted`

**Comment by ajakupov** [comment]
> Installing collected packages: cytoolz, pyphen, regex, dill, ujson, pathlib, plac, termcolor, thinc, spacy, unidecode, python-levenshtein, textacy
  Found existing installation: cytoolz 0.7.3
    DEPRECATION: Uninstalling a distutils installed project (cytoolz) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling cytoolz-0.7.3:
      Successfully uninstalled cytoolz-0.7.3
  Rolling back uninstall of cytoolz
Exception:
Traceback (most recent call last):
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/nbcommon/anaconda3_23/lib/python3.4/site-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted

**Comment by bdewilde** [comment]
Hi @ajakupov , I'm not familiar with installing / uninstalling Python packages from within a Jupyter notebook using an Anaconda version of Python 3.4. In fact, I've never done an installation in any of those environments _individually_. The problem arises for `cytoolz`, but I'm pretty sure that's just because it's the first package in the list.

Can you install `textacy` in the same environment in which you're running the notebook, but not within the notebook?

**Comment by gryBox** [comment]
@ajakupov - You need to install `textacy`, (or any other package), from the command line.  Not the notebook.  In the `notebook` you import the packages that already installed.

1, 
![image](https://user-images.githubusercontent.com/16763201/31782056-815f4e82-b4bf-11e7-824e-dba867dc1f3c.png)

2,  `import textacy` in the notebook

**Comment by gryBox** [comment]
If it's still giving you issues.  Install textacy from conda. It will be
version 3.4.   That will install all the dependencies properly.  From here
you have two choices, keep textacy v 3.4 or uninstall and reinstall textacy
with pip for version 4.x.

Itay Livni

**Comment by ajakupov** [comment]
Thank you @gryBox for your response but the issue is that I am using the Azure Notebook, so I have no idea of what the environment look like. With command line it is fine but still doesn't solve the problem

**Comment by go-bears** [comment]
Hello, I'm also having problems with using textacy in a jupyter notebook. I installed textacy with conda, and it seems to work on the command line in the environment
<img width="512" alt="screen shot 2017-10-29 at 9 36 40 am" src="https://user-images.githubusercontent.com/6887377/32145884-c8b05e14-bc8c-11e7-8c96-3c543f0c82da.png">

BUT the same import in the jupyter notebook has an attribute error with scipy.sparse
<img width="828" alt="screen shot 2017-10-29 at 9 32 52 am" src="https://user-images.githubusercontent.com/6887377/32145887-e1cb0d5e-bc8c-11e7-9bcc-0b38dc629f46.png">

I checked that both command line and the notebook using the same python in the environment with <code>which python</code> and they are. I even tried to import scipy.sparse within the topic_modelling.py but still getting the same error in the jupyter notebook.  Thanks for any guidance!

**Comment by bdewilde** [comment]
Hi @go-bears , this doesn't appear to be a `jupyter notebook` issue, but a `scipy` version issue. `textacy` requires `scipy>=0.17`, and that should be handled automatically when you install `textacy` — what version of `scipy` are you using?

**Comment by go-bears** [comment]
Hi bdewilde! thanks for looking into this! conda says I two versions of scipy
scipy                     0.19.1              np113py36_0  
scipy                     1.0.0                     <pip>

but both are > 0.17 ??

**Comment by bdewilde** [comment]
Okay, that's strange: I can do `import scipy.sparse as sp` in both of those versions, without raising the exception you posted. (Note: I don't know if `scipy 0.19.1` is different from `scipy 0.19.1 np113py36_0`.) Did you check the version imported within the notebook itself? e.g.

```
>>> import scipy
>>> scipy.__version__
'1.0.0'
```

Or did you check from the command line via `conda`? If the latter, please double-check within the env you're using for the import — there could be a mismatch, which to me would indicate that something fishy's going on with your python dev setup. I don't use `conda`, so it's hard for me to debug...

**Comment by go-bears** [comment]
Hi! 
i did check via conda and just checked again from within the environment (on command-line and in the notebook) and both are coming up as 1.0.0 which was installed by pip. <code>import scipy.sparse</code> works from both as well.  
Yeah, it's weird! I can access scipy.sparse manually but scipy's own module can't find itself. But issue only came up during textacy install.

**Comment by go-bears** [comment]
looks like Jupyter notebook like textacy as import now! after the poking as recommende, thanks @bdewilde !  appreciate the time you took to help out!

**Comment by bdewilde** [comment]
Just checking: Does this help anyone? /05/installing-python-packages-from-jupyter/

**Comment by ajakupov** [comment]
Well, the same for me. Changing the kernel to python 2.7 solved the issue. Thank you!
