### ISSUE TITLE
Bug in replace_currency_symbols

### ISSUE THREAD

**Issue by elrasp** [chartbeat-labs/textacy#137]
When the _replace_currency_symbols_ method is passed with a _replace_with_ parameter, the letter 'z' in any word is replaced by _replace_with_ 

## Expected Behavior
A word containing the letter 'z' should not be affected by the _replace_currency_symbols_ method

## Current Behavior
Any word containing the letter 'z' is replaced by the _replace_with_ parameter 

## Possible Solution
The CURRENCY_REGEX needs to be improved
 
## Steps to Reproduce (for bugs)
Here is a sample test case

```

from unittest import TestCase
import textacy.preprocess as preprocess

class TestTransformerUtils(TestCase):

    def test_run_replace_symbols(self):
        result = preprocess.replace_currency_symbols("zebra", "CURRENCY")
        self.assertEqual(result, "zebra")
```

This is the error that the test gives 

```
======================================================================
FAIL: test_run_replace_symbols (tests.test_transformers.TestTransformerUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/test_transformers.py", line 8, in test_run_replace_symbols
    self.assertEqual(result, "zebra")
AssertionError: 'CURRENCYebra' != 'zebra'
- CURRENCYebra
+ zebra

```

## Context
Errors in pre-processing where normalization of currencies is needed

## Your Environment
{'platform': 'linux',
 'python': '3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]',
 'spacy': '1.9.0',
 'spacy_models': ['en-1.1.0', 'en'],
 'textacy': '0.3.4'}

**Comment by bdewilde** [comment]
Hey @elrasp , thanks for the bug report. I see the problem — my regex assumes that all currency symbols are a single char, but `zł`is an exception, and that `z` gives rise to your issue. It's not immediately clear how to fix it, but I'll figure it out.

**Comment by elrasp** [comment]
Would it be better if the regex matched all the currency symbols using `\p{Sc}`? But however in this case I don't think it matches with `zł`
