### ISSUE TITLE
emotional_valence() directory error

### ISSUE THREAD

**Issue by bdewilde** [chartbeat-labs/textacy#138]
_Submitted via email:_

I have run into a problem in textacy. When I try to use the function `lexicon_methods.emotional_valence(text)`

I get the error message

```
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/textacy/resources'
```

But the file `/resources` does not exist. Not in my installation at least. Do you have an idea of what might be wrong here?

**Comment by bdewilde** [comment]
In short, you need to download the `DepecheMood` dataset before using it to get emotional valence scores, and it has to be a directory you can write to.

That said, the way I've written the relevant code is weird, and I should update it to something more sensible. I could follow the pattern set by the `Dataset` classes, or look to `spacy` for guidance.

**Comment by ddofer** [comment]
I get errors when trying to loaod the textacy.data module at all.

```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-123-10d5b7a212bd> in <module>()
----> 1 from textacy import data

~/anaconda/lib/python3.6/site-packages/textacy/data.py in <module>()
     27 LOGGER = logging.getLogger(__name__)
     28 
---> 29 DEFAULT_DATA_DIR = textacy.__resources_dir__
     30 
     31 _CACHE = {}

> AttributeError: module 'textacy' has no attribute '__resources_dir__'
```
