### ISSUE TITLE
textacy and utf8

### ISSUE THREAD

**Issue by macbuse** [chartbeat-labs/textacy#139]
## Expected Behavior

textacy.text_utils.keyword_in_context should behave
consistently independantly of what the default encoding
is.

## Current Behavior

textacy.text_utils.keyword_in_context
has inconsistent behavior: 
 after calling sys.setdefaultencoding('utf8')
it returns a NoneType

## Steps to Reproduce (for bugs)

The code/output is here :
https://github.com/macbuse/NLP/blob/master/textacy_bug.ipynb

## Your Environment

{'platform': 'darwin',
 'python': '2.7.13 |Anaconda, Inc.| (default, Sep 21 2017, 17:38:20) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]',
 'spacy': '1.9.0',
 'spacy_models': ['en-1.1.0'],
 'textacy': '0.3.4'}

**Comment by bdewilde** [comment]
Hi @macbuse , This is one of the stranger issues I've seen... I was able to reproduce it in Python 2, although fundamentally I don't know what's going wrong. I'll note that The Internet suggests that [messing with `sys.setdefaultencoding` can be fraught](https://stackoverflow.com/questions/28657010/dangers-of-sys-setdefaultencodingutf-8). That said, there's a workaround: If you set `print_only=False` in the call to `keyword_in_context()`, you actually _do_ get the results back as an iterable:

```
>>> import sys
>>> reload(sys)
>>> sys.setdefaultencoding('utf-8')
>>> list(text_utils.keyword_in_context(text_ss, 'image', window_width=35, print_only=False))
[(u'Fan Xi: Reduction of ', u'Image', u' - Return to the essence of image\nF'),
 (u'f Image - Return to the essence of ',
  u'image',
  u'\nFan Xi\u2019s solo exhibition at Yang G'),
 (u'tion at Yang Gallery \u201cReduction of ',
  u'Image',
  u'\u201d is a collection of photographic w'),
 (u'ipal series of works "Reduction of ',
  u'Image',
  u'", "Duration", "Tree" and "All Bein'),
...
]
```

**Comment by macbuse** [comment]
Hi

thanks for replying - I really like spacy/textacy

On 15 November 2017 at 01:52, Burton DeWilde <notifications@github.com>
wrote:

> Hi @macbuse <https://github.com/macbuse> , This is one of the stranger
> issues I've seen... I was able to reproduce it in Python 2, although
> fundamentally I don't know what's going wrong. I'll note that The Internet
> suggests that messing with sys.setdefaultencoding can be fraught
> <https://stackoverflow.com/questions/28657010/dangers-of-sys-setdefaultencodingutf-8>
> .
>
I think it is *quick and dirty*  but I've had problems
with printing in  unicode  whatever I do :

>import codecs
>UTF8Writer = codecs.getwriter('utf8')
>sys.stdout = UTF8Writer(sys.stdout)

doesn't work.

 That said, there's a workaround: If you set print_only=False in the call
to keyword_in_context(), you actually *do* get the results back as an
iterable:

Thanks (but strange) .

Keep up the good work.

Best



> greg mc

Grenoble France

https://www-fourier.ujf-grenoble.fr/~mcshane/
