### ISSUE TITLE
Upgrade to spacy 2.x

### ISSUE THREAD

**Issue by hobofan** [chartbeat-labs/textacy#141]
Wanted to try out textacy and noticed it wasn't spacy 2.x compatible (not too unexpected, since it has only been out for a week).

There seem to be quite a few items on the [list of breaking changes and migration notes](https://spacy.io/usage/v2#incompat), but I don't know how strongly textacy is affected here.

**Comment by bdewilde** [comment]
Hi @hobofan , updating `textacy` to use `spacy>=2.0` is currently underway, but it'll take me a bit. I'm going through their new docs looking for 1. required changes and 2. opportunities for improvement. Given the modified API and the expanded functionality for hooking directly into the `spacy` pipeline, I'm debating about how best to move forward... Thanks for the nudge!

**Comment by bdewilde** [comment]
Heads-up, I'm almost done making textacy spacy2-compatible, with minimal additional changes. (Will save larger changes for a later release.) You can check my progress here: https://github.com/chartbeat-labs/textacy/pull/142

**Comment by bdewilde** [comment]
Hey @hobofan , just wanted to let you know that textacy's `master` branch is now spacy v2-compatible. I've not published a release to pypi yet because I'd like to make a few more improvements first, but feel free to test it out — and let me know if you run into bugs. :)

**Comment by hobofan** [comment]
@bdewilde Thanks! I wanted to try it out earlier, but wasn't able to figure out how to specify pipenv dependencies on different branches 🙈 . Should be easier now that it's in master! :)
