### ISSUE TITLE
NameError: name 'Vectorizer' is not defined

### ISSUE THREAD

**Issue by EitanSht** [chartbeat-labs/textacy#146]
## Expected Behavior

Following the examples from the site, on Topic Modelling:
> http://textacy.readthedocs.io/en/stable/api_reference.html#module-textacy.tm.topic_model

Can't make it work.
## Current Behavior

![image](https://user-images.githubusercontent.com/20167064/33787225-040201e0-dc75-11e7-98fb-30a5f24e61a9.png)

## Your Environment

- 'platform': 'win32',
-  'python': '3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]',
-  'spacy': '1.9.0',
-  'spacy_models': ['en'],
-  'textacy': '0.3.4'

**Comment by bdewilde** [comment]
Hi @EitanSht , I can't reproduce your error using the most recent version of textacy, and I'm pretty sure that the version you're using (0.3.4) is not the one whose docs you're following. I recommend updating your version and trying again. Could you let me know if that works?

**Comment by bdewilde** [comment]
Scratch that — I'm _positive_ it's an issue with your version. The `Vectorizer` class was added in v0.4.0.

**Comment by EitanSht** [comment]
You were correct.
Updated Textacy to 0.5.0 and it works well.
The only change I had to make is to add 'textacy': 
`textacy.Vectorize`

Thank you for the quick response.
