### ISSUE TITLE
Textacy unable to create corpus from a textacy.doc.Doc class

### ISSUE THREAD

**Issue by peachyDinosaur** [chartbeat-labs/textacy#147]
I'm just working thought the text tutorials with data outside the datasets module for work. I get some text data from a dataframe and I have this stored as a string variable for work. 

    def mergeText(df):
        content = ''
        for i in df['textColumn']:
            content += (i + '. ' )
        #print(content)
        return content

     
     txt = mergeText(df)

I've worked with spacy a little and I know this is the standard way to create a doc object

    nlp = spacy.load('en')
    doc1 = nlp(txt)
    print(type(doc1))

which outputs

    class 'spacy.tokens.doc.Doc

So I should be able to generate a corpus from this doc file as the documentation says 

    corpus = textacy.corpus.Corpus('en', docs=doc1)

But I get this error even though I'm passing the correct type to the function

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-8-c6f568014162> in <module>()
    ----> 1 corpus = textacy.corpus.Corpus('en', docs=doc1, metadatas=None)
    
    ~/anaconda3/envs/nlp/lib/python3.6/site-packages/textacy/corpus.py in __init__(self, lang, texts, docs, metadatas)
        156             else:
        157                 for doc in docs:
    --> 158                     self.add_doc(doc)
        159 
        160     def __repr__(self):
    
    ~/anaconda3/envs/nlp/lib/python3.6/site-packages/textacy/corpus.py in add_doc(self, doc, metadata)
        337             msg = '`doc` must be {}, not "{}"'.format(
        338                 {Doc, SpacyDoc}, type(doc))
    --> 339             raise ValueError(msg)
        340 
        341     #################
    
    ValueError: `doc` must be {<class 'textacy.doc.Doc'>, <class 'spacy.tokens.doc.Doc'>}, not "<class 'spacy.tokens.token.Token'>"

I have tried to create a textacy object in the same way but with no luck

    doc = textacy.Doc(txt)
    print(type(doc))
    
    <class 'spacy.tokens.doc.Doc'>

I also tried to use the texts paramater for the corpus passing it the raw text but this outputs 

    corpus[:10]

    [Doc(1 tokens; "D"),
     Doc(1 tokens; "e"),
     Doc(1 tokens; "a"),
     Doc(1 tokens; "r"),
     Doc(1 tokens; " "),
     Doc(1 tokens; "C"),
     Doc(1 tokens; "h"),
     Doc(1 tokens; "r"),
     Doc(1 tokens; "i"),
     Doc(1 tokens; "s")]

Any ideas on how to fix this ?

**Comment by bdewilde** [comment]
Hey @peachyDinosaur , the `docs` passed into `Corpus()` must be an iterable of docs, not just a single doc, as specified in the docstring. In your code, you're passing an object that _is_ iterable, but each item is a single token.

You can do `corpus = textacy.corpus.Corpus('en', docs=[doc1])` to move forward.
