### ISSUE TITLE
Memory leak when repeatedly calling doc.count() over a large corpus

### ISSUE THREAD

**Issue by adrianog** [chartbeat-labs/textacy#150]
Memory usage seems to keep on growing when it shouldn't.

## Expected Behavior
Memory usage should stay more or less constant, not creep up.

## Current Behavior
Memory usage creeps up.

## Possible Solution
...

## Steps to Reproduce (for bugs)

```import textacy.doc

import textacy.datasets.supreme_court


terms_to_check = dict.fromkeys((
"21 Oct 2015",
"Initialization is the",
"stage",
"of object creation",
"that",
"makes a newly allocated object usable",
"by setting its state",
"to reasonable initial",
"values",
"Initialization.",
"should always",
"occur right after allocation.",
"It is performed",
"by",
"an initializer",
"eismycin",
"method",
"(or simply,",
"an initializer),",
"always invoke on a newly allocated object.",
"The Swift Programming Language (Swift",
"4.0.3): Initialization",
"brl 4910a",
"brl4910a",
"centany",
"The job",
"mupirocine",
"pibaksin"),0)

sc = textacy.datasets.supreme_court.SupremeCourt()
sc.download()
sc.info

for text in sc.texts():
  
  current__textacy_doc = textacy.doc.Doc(
    text,
    lang="en"
  )
  for key in terms_to_check:
    current__textacy_doc.count(key)

```

If I change:

```
for text in sc.texts():
  current__textacy_doc = textacy.doc.Doc(
    text,
    lang="en"
  )
  for key in terms_to_check:
    current__textacy_doc.count(key)
```

To:

```
for text in sc.texts():
  current__textacy_doc = textacy.doc.Doc(
    text,
    lang="en"
  )
```

Then memory does not creep up. So it looks like definitively a side-effect of `doc.count(term)`

## Context
Calculating matches over a large corpus.

## Your Environment
{'python': '3.5.2 (default, Nov 17 2016, 17:05:23) \n[GCC 5.4.0 20160609]', 'textacy': '0.5.0', 'platform': 'linux', 'spacy_models': ['en'], 'spacy': '2.0.5'}

**Comment by bdewilde** [comment]
Hi @adrianog , how large is this "creeping" upward?

When you call `Doc.count(some_term)`, all terms in the document of the same length as `some_term` are added to the underlying spacy stringstore if they haven't already been, and it's possible that this is to blame. Streaming memory growth of the stringstore is a very longstanding issue that _recently_ got a fix. (See PR # 1424 at https://github.com/explosion/spaCy/pulls)

No obvious solution comes to mind for this, but if the increase in memory usage is relatively small,  is it a thing we could live with?

**Comment by adrianog** [comment]
I see, thanks for the insight. I see the pull request here https://github.com/explosion/spaCy/pull/1424.

Memory peaks out at around 64gb with 1300 documents (my intention was to process 25000) - but I am checking 50000 `some_term`s, with all kind of token counts (some in the tens); so I can see how this would cause memory to shoot up.

I've re-implemented the same functionality using PhraseMatcher from Spacy, and it doesn't suffer from the same problem. In fairness, the `some_term` token count is limited to 10 in PhraseMatcher, but in any case, I notice _no memory increase at all_, which I suspect indicates Spacy is not using the StringStore in the same way textacy does when precaching all the ngrams of size `someterm` token count.

As a workaround one could check for memory available and reset the stringstore (destroy/recreate), or at a given batch size (say 500 documents in my case).

**Comment by adrianog** [comment]
Hi

Has anything changed in the latest versions of (spacy|textacy) that would affect this behaviour?
Thanks

**Comment by bdewilde** [comment]
This functionality hasn't changed in textacy — pull requests welcome! — but I can't speak for spacy.
