### ISSUE TITLE
Serious lack of examples and how-tos

### ISSUE THREAD

**Issue by colingoldberg** [chartbeat-labs/textacy#160]
There is a serious lack of examples and 'how to' articles to help new users get started.

For example: Having installed textacy on macosx (High Sierra 10.13.2) using conda (as instructed in the readme doc), I thought I would experiment with loading a corpus.

I got stuck at 'import textacy.datasets'
ModuleNotFoundError: No module named 'textacy.datasets'

How do I install textacy.datasets?

And in trying to provide environment details
- with textacy.utils.print_markdown(textacy.utils.get_config())
AttributeError: module 'textacy' has no attribute 'utils'

Any help is appreciated.

## Your Environment

AttributeError: module 'textacy' has no attribute 'utils'

- operating system: macosx (High Sierra 10.13.2)
- python version: Python 3.6.4 |Anaconda custom (64-bit)| (default, Dec 21 2017, 15:39:08)
- `spacy` version: spacy-1.9.0
- installed `spacy` models:
- `textacy` version: textacy-0.3.4

**Comment by bdewilde** [comment]
Hi @colingoldberg , sorry about the trouble. You're right: I could _really_ use more end-to-end examples using `textacy`. For what it's worth, I opened an issue about it last summer (https://github.com/chartbeat-labs/textacy/issues/117), and marked it as "help wanted". Submissions welcome!

As for your specific issues... You're using older versions of `textacy` and `spacy` that don't match up with the documentation you're following, so I wouldn't expect everything to just work. I can't do much about this, other than make it easy for folks to match docs with their installed versions. Unfortunately, for the past few months, the official ReadTheDocs site hasn't been able to build updated docs bc of server issues on their side, which may be leading to confusion on users' sides. I'll try to prioritize getting ReadTheDocs to work, or finding something else to replace it.

**Comment by adrianog** [comment]
For what is worth, in my container this runs ok:

```
root@7edb7b00d9f9:/# pip3 freeze | grep -i textacy
textacy==0.5.0
root@7edb7b00d9f9:/# python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import
KeyboardInterrupt
>>> import textacy.datasets
>>>
>>>
```

I have found working with containers much more stress-free compared to dealing with native installs, virtualenv notwithstanding.
