### ISSUE TITLE
Index of each n-gram in the original text when extracted by textacy.extract.ngrams with filter_stops or  filter_punct are TRUE

### ISSUE THREAD

**Issue by KMohaghegh** [chartbeat-labs/textacy#162]
I am using textacy.extract.ngrams to get the n-grams from a doc with both filter_stops and  filter_punct
are True. Let's say that the function generates 100 n-grams for us, I am interested to print all this ngrams side wise the original text which **has** the STOP_WORD and/or Punctuation. In other word I am interested to have access to the index of each n-grams inside the original text to call and print. So if I know that each of those 100 n-grams start with which index and end in which index (in the original text) simply I could print from starting token  till end token in the original text at least.
Hope some one could help me with that. Could be an textacy/Spacy command to make it or even just purely python tips. Anything not so time consuming are really appreciated as I work with a huge data sets.

 
- operating system: Mac high Sierra 10.13.1
- python version: 2.7.13
- `spacy` version: 2.0.5
- installed `spacy` models:
- `textacy` version: last version

**Comment by bdewilde** [comment]
Hi @KMohaghegh , `textacy.extract.ngrams` yields spaCy `Span` objects, which have [functionality that should meet your needs](https://spacy.io/api/span#attributes). Specifically, each ngram has `.start` and `.end` attributes, which give the indexes of the first and last tokens in the tokenized document, as well as `.start_char` and `.end_char` attributes, which give the indexes of the first and last characters in the raw text.

Here's  a code sample to show you what I mean.

```
>>> text = "I am using textacy.extract.ngrams to get the n-grams from a doc with both filter_stops and filter_punct are True. Let's say that the function generates 100 n-grams for us, I am interested to print all this ngrams side wise the original text which has the STOP_WORD and/or Punctuation."
>>> doc = textacy.Doc(text)
>>> ngrams = textacy.extract.ngrams(doc, 3, filter_stops=True, filter_punct=True)
>>> idx = 0
>>> for ngram in ngrams:
...     while idx < ngram.start:
...         print(idx, doc[idx])
...         idx += 1
...     print('{}-{} {}'.format(ngram.start, ngram.end, ngram))
...     idx += len(ngram)
0 I
1 am
2 using
3 textacy.extract.ngrams
4 to
5 get
6 the
7 n
8 -
9 grams
10 from
11 a
12 doc
13 with
14 both
15-18 filter_stops and filter_punct
17-20 filter_punct are True
21 Let
22 's
23 say
24 that
25 the
26-29 function generates 100
27-30 generates 100 n
32 for
33 us
34 ,
35-38 I am interested
37-40 interested to print
41 this
42-45 ngrams side wise
44-47 wise the original
48 which
49 has
50 the
51-54 STOP_WORD and/or Punctuation
```

I'm going to close this issue out, but if the above doesn't resolve your issue, please re-open and point me back in the right direction.

**Comment by KMohaghegh** [comment]
Really thanks for your reply, I will try this today and let you know.
