### ISSUE TITLE
Regarding a closed issue  #162, having question after testing

### ISSUE THREAD

**Issue by KMohaghegh** [chartbeat-labs/textacy#164]
My issue is back to the closed issue number #162.
First of all the reply the owner (bdewilde) mentioned was very useful, but I have a problem. When you look at the results,  you see that inside n-grams printed you  see STOP_WORDS like:
"15-18 filter_stops and filter_punct" the STOP_WORD "and" is in first found 3-gram. I am interested to get all my three grams without stop_words. Thats why I did not use "filter_stops=True" and instead use the following command 
doc_1 = ' '.join([word for word in mytext.split() if word not in STOP_WORDS])
then send doc_1 to the textacy.extract.ngrams() and make the filter off (filter_stops=False) as I am sure there is no stop_word exist on the text. Then the index send back by textacy.extract.ngrams is not accurate as it always back to the text without stop_word. I want either all my n-gramm without any stop_word or if I continue with my version some how the got the begin and end ngram has which index in the original text. To simplify something like this:

1-"I have problem with ngram stuff and I hope you solve it for me"
2-after stop_word removal it is become:
"problem ngram stuff hope  solve"
3-three-gram will be:
[problem ngram stuff][ngram stuff hope][stuff hope solve]
4-Index I want
(I startle index from 1 not zero!)
first ngram starts at [start_index=3 end_index=6]
second ngram starts at [start_index=5 end_index=9]
first ngram starts at [start_index=6 end_index=11]

I make a logic at the moment that when it produce the n-gramms without STOP_WORDs it is also iterate and find the index in the original text but as my corpus is huge it will extremely time consuming.
The idea of "bdewilde" at #162 is really helpful and solve the number 4 above but did not give me ngram as number three. If at least give me without stop_word but not all the ngrams that somehow might works for me. 
Sorry that it is this long but wants to get you all the perspective of my problem.

Thanks for your help and comments. Versions and machines and ... is the same as #162.

**Comment by bdewilde** [comment]
Hi @KMohaghegh ,

As stated in the docs for `extract.ngrams()`, setting `filter_stops=True` only filters out ngrams whose first or last word is a stop word. For example, "bdewilde and Kmohaghegh" passes this condition, while "and Kmohaghegh asked" does not. For most purposes, this is good and sensible behavior.

In your message, you create `doc_1` as a string of non-stop words, but that isn't a valid input to `extract.ngrams()`, where `doc` must be a textacy or spacy `Doc`. If the function manages to return an output without crashing, it certainly isn't useful, given the bad inputs:

```
In [4]: list(textacy.extract.ngrams("I have problem with ngram stuff and I hope you solve it for me".split(), 2))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-966a174148c6> in <module>()
----> 1 list(textacy.extract.ngrams("I have problem with ngram stuff and I hope you solve it for me".split(), 2))

~/chartbeat/github/textacy/textacy/extract.py in ngrams(doc, n, filter_stops, filter_punct, filter_nums, include_pos, exclude_pos, min_freq)
    175                    if freqs[ngram.lower_] >= min_freq)
    176
--> 177     for ngram in ngrams_:
    178         yield ngram
    179

~/chartbeat/github/textacy/textacy/extract.py in <genexpr>(.0)
    140                    if not ngram[0].is_stop and not ngram[-1].is_stop)
    141     if filter_punct is True:
--> 142         ngrams_ = (ngram for ngram in ngrams_
    143                    if not any(w.is_punct for w in ngram))
    144     if filter_nums is True:

~/chartbeat/github/textacy/textacy/extract.py in <genexpr>(.0)
    137                if not any(w.is_space for w in ngram))
    138     if filter_stops is True:
--> 139         ngrams_ = (ngram for ngram in ngrams_
    140                    if not ngram[0].is_stop and not ngram[-1].is_stop)
    141     if filter_punct is True:

~/chartbeat/github/textacy/textacy/extract.py in <genexpr>(.0)
    135                for i in compat.range_(len(doc) - n + 1))
    136     ngrams_ = (ngram for ngram in ngrams_
--> 137                if not any(w.is_space for w in ngram))
    138     if filter_stops is True:
    139         ngrams_ = (ngram for ngram in ngrams_

~/chartbeat/github/textacy/textacy/extract.py in <genexpr>(.0)
    135                for i in compat.range_(len(doc) - n + 1))
    136     ngrams_ = (ngram for ngram in ngrams_
--> 137                if not any(w.is_space for w in ngram))
    138     if filter_stops is True:
    139         ngrams_ = (ngram for ngram in ngrams_

AttributeError: 'str' object has no attribute 'is_space'
```

You can try to create a proper `Doc` from the text with stop words removed, but I wouldn't expect spaCy to do a good job with part-of-speech tagging, parsing, etc. given the modified text. YMMV.

Ngrams are typically _contiguous_ groups of words, but what you're trying to do is waive the contiguous requirement and group words that may be separated by stop words. `textacy` doesn't have anything special to handle this use case.

**Comment by KMohaghegh** [comment]
Thanks, but I am not interested on  part-of-speech tagging, parsing, etc. on these n-gram, I use it just to get the same size list and cover the whole document.
