### ISSUE TITLE
QUESTION: Get POS tags quickly out of doc.pos_tagged_text

### ISSUE THREAD

**Issue by andyherzberg** [chartbeat-labs/textacy#165]
Hi there, 
Firstly: thanks for textacy which is a great tool :)
I am looking for a way to get the sums of the POS tags for a text quickly. I read about the textasy .count function which should be able to do what I want but I can't get it to work. 

Currently I have 
```
doc = textacy.Doc(mytext, lang='de')
sum_ = 0

for i in range (0, len(doc.pos_tagged_text)):
    sum_ += sum([x[1].count('NOUN') for x in doc.pos_tagged_text[i]])

print (sum_)
```
I takes ages untilI get the values out there. Can you give me an advice on how to archive this quickly?

## Expected Behavior
The textacy .count function can be used for counting the POS tags quickly.

Thanks a lot and have a great day!

**Comment by bdewilde** [comment]
Hey, `Doc.count()` is for getting the number of occurrences of a particular term in the document — it's _not_ set up to get counts for particular parts-of-speech. This (or something like it) is probably what you want to to do:

```
doc = textacy.Doc(yourtext, lang='de')

import collections

counts = collections.Counter(tok.pos_ for tok in doc)
print(counts['NOUN'])
```

**Comment by andyherzberg** [comment]
That's exactly what I was searching for 👍 
THANKS A LOT :)
