### ISSUE TITLE
Wikipedia.texts() does not strip some HTML and CSS

### ISSUE THREAD

**Issue by jbingel** [chartbeat-labs/textacy#166]
Using `.texts()` on a `Wikipedia` instance, some HTML and CSS is not stripped (especially in what seems to be tables). Example:

    >>> from textacy.datasets.wikipedia import *
    >>> wpd = Wikipedia(lang='haw')
    >>> wpd.download()
    >>> txts = list(wpd.texts())
    >>> print(txts[0])
    Ussuk
    
    {| border=1 align=right cellpadding=4 cellspacing=0 width=300 style="margin: 0 0 1em 1em; background:     #f9f9f9; border: 1px #aaaaaa solid; border-collapse: collapse; font-size: 95%;"
    
     <big>Ussuk</big> <br> Erignathus barbatus
     250px
     Kunngeqarfik 
     Animalia
     Siuleriit 
     Chordata
     Inuiaqatigiinni <br>inissisimanerit 
     Mammalia 
     Tullerit 
     Pinnipedia
     Ilatutariit 
     Phocidae 
     Kinguaarit 
     Erignathus 
     Pissuseqatigiit 
     E. barbatus 
     250px

## Expected Behavior
The CSS in output line 3, the HTML tags in the listing and the CSS values in the listing should not be returned.

## Current Behavior
see above

## Possible Solution
Fix regexes in `textacy.datasets.wikipedia` ?

## Steps to Reproduce (for bugs)
see above

## Context
Trying to get clean WPD text to build a language model

## Your Environment

- operating system: Ubuntu 16.04
- python version: 3.5.2 (Anaconda)
- `spacy` version: 2.0.8
- installed `spacy` models: 'en'
- `textacy` version: 0.5.0

**Comment by bdewilde** [comment]
Hi @jbingel , last I tried, this proved to be a surprisingly tricky problem — and wikimarkup tables are particularly difficult to handle in all cases. I don't have a good solution for you. But, I can add this to my backlog as something to revisit.

**Comment by jbingel** [comment]
Thanks! Yeah I can imagine this is not easy. The bogus HTML could easily be grepped, at least in the form it's present in the example above, but for that CSS... meh. One could perhaps try to use CSS's vocabulary? I understand being too aggressive here may strip away some of the text we'd normally want to keep, but for some use cases (e.g. language modelling) that probably wouldn't be a big issue.

**Comment by bdewilde** [comment]
A couple months ago I significantly reworked this dataset, and it should have solved your issue. Hope this helps. https://chartbeat-labs.github.io/textacy/api_reference/datasets.html#textacy.datasets.wikimedia.Wikipedia
