### ISSUE TITLE
Textacy import error on Python Jupyter notebooks

### ISSUE THREAD

**Issue by NataliaDiaz** [chartbeat-labs/textacy#17]
Hi, I am running on OSX Python  2.7 Jupyter notebook on docker container and after installing all textacy libraries, still get this error. What can it be?Thanks!

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-b8a2c2357440> in <module>()
import spacy
# Set up spaCy
from spacy.en import English
...
---> 28 import textacy

/usr/local/lib/python2.7/site-packages/textacy/__init__.py in <module>()
      8 
      9 # subpackages
---> 10 from textacy import corpora
     11 from textacy import fileio
     12 from textacy import representations

/usr/local/lib/python2.7/site-packages/textacy/corpora/__init__.py in <module>()
----> 1 from . import wikipedia
      2 from .bernie_and_hillary import fetch_bernie_and_hillary

ImportError: cannot import name wikipedia
```

**Comment by bdewilde** [comment]
Hi @NataliaDiaz, I'm honestly not sure what's going wrong. What's the exact line of code you're calling that causes this error? Also, which versions of textacy and spaCy are you using? The latest are 0.2.2 and 0.101.0, respectively.

**Comment by chssch** [comment]
Hey,

I had a similar problem when installing with pip.

Could it be that the dependencies at https://github.com/chartbeat-labs/textacy/blob/master/setup.py#L39 are not complete? (just had a quick look, at least gensim is not listed there, but in the requirements.txt)

Workaround (worked for me): 
get https://github.com/chartbeat-labs/textacy/blob/master/requirements.txt and do a

`pip install -r requirements.txt`

**Comment by bdewilde** [comment]
@chssch I was wondering if that might be the issue, although the error message that the original poster gave didn't seem to indicate it. Thanks for commenting! It's been a low priority to get the setup.py requirements sorted, but I'll push this up. In the meantime, @NataliaDiaz: Could you try installing all dependencies given in the requirements file, i.e. `pip install -r requirements.txt`, then importing textacy?

**Comment by bdewilde** [comment]
By the way, I've pushed a change to master that adds in the missing dependencies into the setup.py script. Feel free to try out the dev version on master!

**Comment by chssch** [comment]
Regarding the the exception: I had the same a while ago when installing gensim directly from IPython without restarting the in interpreter/ipython after (it can't fully resolve the import of gensim in wikipedia but isn't able to indicate the exact location). It could be the same problem with Jupyter.

Thanks for the update, it works now great without any additional pip installations. I pushed one of my docker containers to github, maybe it it useful for "clean install" tests. Also maybe useful if somebody with docker just want to check it out quickly.

https://github.com/chssch/textacy-docker

**Comment by bdewilde** [comment]
@chssch Nice! And thank you for confirming that my change fixed the issue. :+1:
