### ISSUE TITLE
After I install textacy. the Spacy is broken.

### ISSUE THREAD

**Issue by kld123509945** [chartbeat-labs/textacy#170]
I installed Spacy before, and it was good to use. Then, after I install textacy, the Spacy is broken.
Here are the two problems I met.
1.When I import Spacy and run the code:

nlp = spacy.load("en")
document = nlp(txt)

The Jupyter notebook inform me as follows:

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-3-a9e428687174> in <module>()
>       1 # load"en"
> ----> 2 nlp = spacy.load("en")
>       3 document = nlp(txt)
> 
> ~\Anaconda3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
>      40     overrides['meta'] = meta
>      41     overrides['path'] = model_path
> ---> 42     return cls(**overrides)
> 
> ~\Anaconda3\lib\site-packages\spacy\en\__init__.py in __init__(self, **overrides)
>      32         # Special-case hack for loading the GloVe vectors, to support <1.0
>      33         overrides = fix_glove_vectors_loading(overrides)
> ---> 34         Language.__init__(self, **overrides)
> 
> ~\Anaconda3\lib\site-packages\spacy\language.py in __init__(self, **overrides)
>     263 
>     264         self.vocab     = self.Defaults.create_vocab(self) \
> --> 265                          if 'vocab' not in overrides \
>     266                          else overrides['vocab']
>     267         add_vectors    = self.Defaults.add_vectors(self) \
> 
> ~\Anaconda3\lib\site-packages\spacy\language.py in create_vocab(cls, nlp)
>      40         else:
>      41             vocab = Vocab.load(nlp.path, lex_attr_getters=cls.lex_attr_getters,
> ---> 42                              tag_map=cls.tag_map, lemmatizer=lemmatizer)
>      43         for tag_str, exc in cls.morph_rules.items():
>      44             for orth_str, attrs in exc.items():
> 
> ~\Anaconda3\lib\site-packages\spacy\vocab.pyx in spacy.vocab.Vocab.load (spacy/vocab.cpp:4742)()
> 
> ~\Anaconda3\lib\pathlib.py in open(self, mode, buffering, encoding, errors, newline)
>    1159             self._raise_closed()
>    1160         return io.open(str(self), mode, buffering, encoding, errors, newline,
> -> 1161                        opener=self._opener)
>    1162 
>    1163     def read_bytes(self):
> 
> ~\Anaconda3\lib\pathlib.py in _opener(self, name, flags, mode)
>    1013     def _opener(self, name, flags, mode=0o666):
>    1014         # A stub for the opener argument to built-in open()
> -> 1015         return self._accessor.open(self, flags, mode)
>    1016 
>    1017     def _raw_open(self, flags, mode=0o777):
> 
> ~\Anaconda3\lib\pathlib.py in wrapped(pathobj, *args)
>     385         @functools.wraps(strfunc)
>     386         def wrapped(pathobj, *args):
> --> 387             return strfunc(str(pathobj), *args)
>     388         return staticmethod(wrapped)
>     389 
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\w\\Anaconda3\\lib\\site-packages\\spacy\\data\\en\\vocab\\strings.json'

2.When I run the code of:

> from spacy import displacy

The Jupyter notebook inform me as follows:

ImportError: cannot import name 'displacy'

- operating system: win10
- python version: Anaconda3
- `spacy` version: 1.9.0-np112py36_vc14_1
- installed `spacy` models: en
- `textacy` version: 0.3.4

**Comment by bdewilde** [comment]
Hi @kld123509945 , looks like you're using older versions of textacy and spacy, via anaconda, on windows. That's a lot of differences in your setup compared to my own, so I don't know at a glance what's going wrong here.

Are you able to install textacy and then use spacy in a clean virtual environment?

**Comment by kld123509945** [comment]
Hi @bdewilde, Thanks for your advice! The problems should be blamed on the older versions of textacy and spacy. 
I use the code of  

> conda install  textacy

As the program automatically download the textacy, I noticed that the version of textacy downloaded in this way is a relatively old version. But I cannot imagine that the version is so old to be compatible with the Spacy.
According to your advice, I SHOULD use the code of 

> pip install textacy
Then the problems are all gone. 
The reason I trust conda install is that I think the conda could automatically scan and download the latest version of the code. Now I realize that the code in the conda is always out of date...

**Comment by bdewilde** [comment]
Hey, the version on Anaconda is currently 0.5.0 — see https://anaconda.org/conda-forge/textacy — so, I should probably update it. That said, it's only a couple months old, and as far as I've heard, folks didn't have a problem installing it. I'm going to close this issue out since the problem has resolved with a version upgrade, but will keep an eye out for future problems with conda install.
