### ISSUE TITLE
[Question] Corpus handling

### ISSUE THREAD

**Issue by mobileunit** [chartbeat-labs/textacy#172]
Deal all, 
I created a corpus of a bunch of text that have different metadata as labels. I want to get f. e. the number of sents based on a filtered corpus. I tried:

`corpus.get(lambda doc: doc.metadata['label'] == 'label1').n_sents`

But I get the message "'generator' object has no attribute 'n_tokens'". 

Then I tried to assign the corpus split to another corpus and then get the n_sents by 

```
new_corpus = corpus.get(lambda doc: doc.metadata['label'] == 'label1')
new_corpus.n_sents
```

But then I end up with the same error message  "'generator' object has no attribute 'n_tokens'". 

What am I doing wrong? I think I have some misunderstanding in using the corpus... :/

Many thanks and **BIG** thanks for your help!!!  :)
Andy

**Comment by bdewilde** [comment]
Hi Andy, sorry to leave you hanging — had to neglect `textacy` for a few weeks to focus on other projects.

The interaction you're describing sounds really nice, but unfortunately that's not how the `Corpus` works. When you use `.get()`, it yields each matching doc one at a time, but that's not a `Corpus`. You would have to wrap that generator as a new corpus, which isn't recommended bc it involves overwriting the corpus index on each document.

Just to be clear, you _could_ do something like this:

```
corpus = textacy.Corpus('en', texts=textacy.datasets.CapitolWords().texts(limit=20))
print(corpus)
print('n_sents =', corpus.n_sents)

docs = corpus.get(lambda doc: len(doc) > 500)
new_corpus = textacy.Corpus('en')
for doc in docs:
    new_corpus.add_doc(doc)
    
print(new_corpus)
print('n_sents =', new_corpus.n_sents)
```

... that's not great, I know.

**Comment by bdewilde** [comment]
I've been meaning to improve the `Corpus` class basically since I implemented it. This is a useful reminder of why. Thanks!

**Comment by andyherzberg** [comment]
Hi @bdewilde, 
thanks for getting back to me. Hopefully you find the time someday ;)
By the way: textacy is a great tool :)
Thx
