### ISSUE TITLE
Subject-verb-object extraction example.

### ISSUE THREAD

**Issue by clhl** [chartbeat-labs/textacy#173]
Hi. I'm trying to extract subject-verb-object triplets from a series of tweets, but at the moment am having problems trying to apply it to an example case.

```
import textacy
from textacy.extract import subject_verb_object_triples

text="""Startup companies create jobs and support innovation. Hilary supports entrepreneurship."""
text_ext=textacy.extract.subject_verb_object_triples(text)
list(text_ext)

```

This gives me the error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/textacy/extract.py", line 350, in subject_verb_object_triples
    sents = doc.sents
AttributeError: 'str' object has no attribute 'sents'
```

I saw on another thread it was an issue with string vs unicode on python 2.7 instead of python 3+ so I added the 3rd line to resolve it but still see the same issue. Is it possible to see an example of how to apply this?

If its useful to know down the line I'm trying to apply it to a pandas column to extract the triplets. I'm quite new to python so any advice is appreciated!

Thank you for any help in advance!

**Comment by Pranav95** [comment]
The method expects spacy-parsed doc as input and not python strings. 
You could do something like this:

```
import spacy
import textacy

nlp = spacy.load('en')
text = nlp(u'Startup companies create jobs and support innovation. Hilary supports entrepreneurship.')

text_ext = textacy.extract.subject_verb_object_triples(text)
```

**Comment by clhl** [comment]
Thank you!

This works when I run it for the text string and I added in something to print the result after which works, but when I try it for my pandas column it doesn't. I edited the scripts so that the only change I have between the two scripts working is: `doc = nlp(u'Startup companies create jobs and support innovation. Hilary supports entrepreneurship.')`

Do I need to add something else in the case below to see the output?

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize, wordpunct_tokenize
from nltk.corpus import stopwords
from nltk.metrics import edit_distance
import spacy
import textacy
import csv, string, re
import jsonrpc
import numpy as np
from simplejson import loads
from textblob import TextBlob

#Import csv file
import pandas as pd
df = pd.read_csv("test_1-1.csv", sep=",")
del df['coordinates']

df1 = df['text']
#np.savetxt('/Users/charlottelousada/Documents/Thesis working file/tweets.txt', df.values, fmt=str('%.4e’'))
import StringIO
s = StringIO.StringIO()
tweets = df1.to_csv(encoding='utf-8');

nlp = spacy.load("en")
doc = nlp(u'Jane will eat lunch');

text_ext = textacy.extract.subject_verb_object_triples(doc)
mylist = list(text_ext)
print mylist
```

**Comment by clhl** [comment]
Hi. I actually think I solved the above problem by adding in:
```
df3 = pd.DataFrame(mylist)
df3.columns = ['Subject', 'Verb', 'Object']
print df3
```

But this raised another question I'm struggling with which is - is it possible to keep an ID attached to each result from the initial doc so I can match up the results afterwards?

Thanks again.

**Comment by Mansayy** [comment]
Hey!
If I am using the above code it is working. But it is not working for any other sentence.
Below is the code that I am running:

#SOV
import spacy
import textacy
nlp = spacy.load('en')
text1 = nlp(u'Startup companies create jobs and support innovation. Hilary supports entrepreneurship.')
text2 = nlp(u'Subijanto, a spokesman for Forestry Ministry said Indonesia was committed to protecting the tigers, which live within Sumatra. ')
text_ext1 = textacy.extract.subject_verb_object_triples(text1)
text_ext2 = textacy.extract.subject_verb_object_triples(text2)
a1=list(text_ext1)
a2=list(text_ext2)
print(*a1)
print(*a2)
print("EOF")

I am getting the output for text1 but nothing for text2.
I have attached the output as displayed on my terminal.
Please let me know what I am doing wrong.
![attach](https://user-images.githubusercontent.com/50999982/58368530-0ca53700-7f0c-11e9-87af-0d0853942c23.png)
