### ISSUE TITLE
Wikipedia category extraction for non-English languages

### ISSUE THREAD

**Issue by graus** [chartbeat-labs/textacy#174]
There seems to be hard-coded English handling of Wikipedia metadata (in particular categories, not sure how it affects Files/Images/etc.). I was parsing a German Wikipedia dump and noticed the Category extraction fails. 

Both the regex for cleaning up categories from text ([l.85](https://github.com/chartbeat-labs/textacy/blob/master/textacy/datasets/wikipedia.py#L85)):

    re_categories = re.compile(r'\[\[Category:[^\]\[]*\]\]', flags=re.UNICODE)`

And extracting categories and wikilinks for the 'records' ([l.253](https://github.com/chartbeat-labs/textacy/blob/master/textacy/datasets/wikipedia.py#L253) and [l.256](https://github.com/chartbeat-labs/textacy/blob/master/textacy/datasets/wikipedia.py#L256)) contain the English "Category:"

    parsed_content['categories'] = [wc for wc in wikilinks if wc.startswith('Category:')]

## Possible Solution
Replacing "Category:" with "Kategorie:" fixes category extraction for the German Wikipedia dump. 
I suppose having a (static) mapping from langcodes to "category" labels would be the most obvious fix.

**Comment by bdewilde** [comment]
Hey @graus , thanks for the report! This sort of thing is hard for me to catch, since I've not had occasion to run over German Wikipedia, or learn German. 😅

I think your proposed solution is correct, at least in the short term. I'm currently devoting all my spare cycles to some pro bono data science work, so I can't get to this right away. If you're able and willing, please submit a pull request! Otherwise, I'll get to this as soon as I round up some free time.

**Comment by graus** [comment]
@bdewilde Yes, I can try to submit a PR sometime soon. To solve it for German with the proposed solution would be trivial, but I'd like to see if I can get a more comprehensive mapping for more (the majority of) wiki languages, and see whether this affects anything beyond categories... I'll look into it.

**Comment by sammous** [comment]
Hello, just to say that the same thing happens for French :)
It's  `[[Catégorie: ...]]` for instance.

I think you should put a lookup dictionnary and use the fact that you can access the language from `self.lang` for line [l253](https://github.com/chartbeat-labs/textacy/blob/master/textacy/datasets/wikipedia.py#L253) and [l256](https://github.com/chartbeat-labs/textacy/blob/master/textacy/datasets/wikipedia.py#L256)

```python
LOOK_UP_CAT = {
'en' : 'Category:',
'fr' : 'Catégorie:',
'de': 'Kategorie:',
}
...
parsed_content['categories'] = [wc for wc in wikilinks if wc.startswith(LOOK_UP_CAT[self.lang])]

```

And change the regex to include `OR`.

`re_categories = re.compile(r'\[\[(Category|Catégorie|Kategorie):[^\]\[]*\]\]', flags=re.UNICODE)`

Cheers :)

**Comment by graus** [comment]
ah, @sammous beat me to it! ;-).

PS: why not also incorporate `LOOK_UP_CAT[self.lang]` in `re_categories` as opposed to hardcoding the values in `LOOK_UP_CAT`?

**Comment by sammous** [comment]
Yes i thought exactly with your first solution afterwards :)
I'll update it and check if it works.
thx :)

**Comment by bdewilde** [comment]
Hello! This is now fixed in master. :+1:
