### ISSUE TITLE
Help Needed in  key_terms_from_semantic_network

### ISSUE THREAD

**Issue by swagat123** [chartbeat-labs/textacy#176]
My requirement is to create word cloud , for that i need to extract key phases from the document . This key phases will be used to create word cloud. For extracting key phrases i need help. I saw the information extraction section  in textacy. There are a lot of functionalities added here. I decided to use textacy.keyterms.key_terms_from_semantic_network

i got the below issue 

print(list(textacy.keyterms.key_terms_from_semantic_network(doc, normalize=u'lemma', window_width=2, edge_weighting=u'binary', ranking_algo=u'pagerank', join_key_words=False, n_keyterms=10, **kwargs)))
AttributeError: 'module' object has no attribute 'keyterms

I am using python2.7 
OS - ubantu
textacy (0.5.0)

**Comment by swagat123** [comment]
I got this issue resolved. i have to add import textacy.keyterms , after that all the function under keyterms will be called.  I have a query what will be optimum value for n_keyterms to extract the number of key phrases from the document.

**Comment by bdewilde** [comment]
Hi @swagat123 , I'm glad you figured out the issue. Unfortunately, I can't answer that last question for you — the number of keyterms to extract depends on your use case, the characteristics of the text data you're running over, etc. The function should accept either an absolute value (e.g. 10) or a float between 0 and 1 that will give you a relative percentage of all possible candidates (e.g. 0.1 => 10% of keyterm candidates). It's up to you to figure out what works best for you.
