### ISSUE TITLE
deciding on the number of topics

### ISSUE THREAD

**Issue by jellegrammens** [chartbeat-labs/textacy#178]
Hello,
is there any way i could get a good estimate of the number of topics i should use? Something like an elbow method or something.

**Comment by bdewilde** [comment]
Hi @jellegrammens , that's a classic pain point when it comes to topic models... As far as I know, a dead-simple way to optimize the number of topics is to train multiple models with varying `n_topics`, then score each on a metric indicating the "goodness" of the models — topic coherence is a standard choice — and choose the one with the best score or, as you note, is at the elbow in a distribution, where changing `n_topics` gives diminishing returns.

`gensim` has functionality for this; I never got around to implementing it in `textacy`. I'd love a PR for this, but would understand if you just piggy-backed on gensim to get the job done.
