### ISSUE TITLE
create corpus from spacy docs?

### ISSUE THREAD

**Issue by zkurtz** [chartbeat-labs/textacy#185]
Documentation for the `docs` argument of `textacy.Corpus` ([line 108](https://github.com/chartbeat-labs/textacy/blob/master/textacy/corpus.py)) makes it sound to me like I should be able to make a corpus from a list of spacy docs, but I can't. So I'm not sure if this is a 'how to' or a feature request:

```python

import spacy
import textacy

nlp = spacy.load('en')

doc_strings = [
    'hello World!',
    'We have a problem'
]
docs = [nlp(string.lower()) for string in doc_strings]
corpus = textacy.Corpus('en', docs = docs)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zkurtz/anaconda/lib/python3.6/site-packages/textacy/corpus.py", line 159, in __init__
    self.add_doc(doc)
  File "/Users/zkurtz/anaconda/lib/python3.6/site-packages/textacy/corpus.py", line 333, in add_doc
    raise ValueError(msg)
ValueError: SpacyDoc.vocab <spacy.vocab.Vocab object at 0x11934b4c8> != Corpus.spacy_vocab <spacy.vocab.Vocab object at 0x11d8352c8>
```

Of course I could just do
```python
corpus = textacy.Corpus('en', texts = doc_strings)
```
but my actual use case is large enough for speed to be an issue, and I find that using spacy with `spacy.load('en', disable = ["tagger", "parser", "ner", "textcat"])` is much faster and adequate for my purposes. Alternatively, can I pass that `disable` argument into spacy via `textacy.Corpus` somehow?

**Comment by bdewilde** [comment]
Hi @zkurtz , there's a requirement on docs added to a corpus — expressed in the `ValueError` message — that the spaCy `Vocab` used to create a `Doc` must be the same as the one associated with the `Corpus`. Your example code doesn't do this, because `nlp` is not the same as the equivalent initialized under the hood when you pass `en` in as the language for the `Corpus`.

In this case, there's an easy solution: Initialize the corpus as `textacy.Corpus(nlp, docs=docs)`. Btw, you can load that spacy language pipeline via `textacy.load_spacy("en", disable=[...])`.

**Comment by zkurtz** [comment]
Neither option is working for me:

`textacy.load_spacy("en", disable = ["tagger", "parser", "ner", "textcat"])` is failing with `TypeError: unhashable type: 'list'`

Alternatively, 
```python
import spacy
import textacy

nlp = spacy.load("en", disable=["tagger", "parser", "ner", "textcat"])

doc_strings = [
    'hello World!',
    'We have a problem'
]
docs = [nlp(string.lower()) for string in doc_strings]
corpus = textacy.Corpus(nlp, docs = docs)
```
gives
`KeyError: "No component 'parser' found in pipeline. Available names: []"`

**Comment by bdewilde** [comment]
Hi @zkurtz , the value passed to `disable` has to be a tuple, not a list — this is explained in the function's docstring [here](https://chartbeat-labs.github.io/textacy/api_reference.html#textacy.cache.load_spacy). Sorry if my example `[...]` was misleading.

I'm not sure what to make of your alternative code example or error message. Which version of textacy are you using? What's the full traceback?

**Comment by zkurtz** [comment]
Verified that `nlp = textacy.load_spacy("en", disable = ("tagger", "parser", "ner", "textcat"))` runs. But subsequently `textacy.Corpus(nlp, docs = docs)` leads back to the last error reported above. More details:
```python
>>> spacy.__version__
'2.0.10'
>>> textacy.__version__
'0.6.0'

# The error:  
>>> corpus = textacy.Corpus(nlp, docs = docs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zkurtz/anaconda/lib/python3.6/site-packages/textacy/corpus.py", line 146, in __init__
    self.n_sents = 0 if self.spacy_lang.parser else None
  File "/Users/zkurtz/anaconda/lib/python3.6/site-packages/spacy/language.py", line 180, in parser
    return self.get_pipe('parser')
  File "/Users/zkurtz/anaconda/lib/python3.6/site-packages/spacy/language.py", line 208, in get_pipe
    raise KeyError(msg.format(name, self.pipe_names))
KeyError: "No component 'parser' found in pipeline. Available names: []"
```
Is this what you mean by the full traceback?

**Comment by bdewilde** [comment]
Hi @zkurtz , okay, this makes sense. I've fixed the no-parser bug in master (see https://github.com/chartbeat-labs/textacy/commit/c78a4e1d1ec647a1f1d3988e007a44671d05fae0), but this is after v0.6.0 was released. You can pip install the dev version directly from the repo; otherwise, you'll have to hang in there until I release v0.6.1. This is in the works, but it'll be another couple weeks at least.

**Comment by rafaleo** [comment]
I've got strange error using the above code for my data (5 strings in a list): 
ValueError: SpacyDoc.vocab <spacy.vocab.Vocab object at 0x000000003C6CA3C8> != Corpus.spacy_vocab <spacy.vocab.Vocab object at 0x000000002225C6C8>
```
Downloading and Extracting Packages
cachetools-3.1.0     | 11 KB     | ############################################################################ | 100%
spacy-2.0.11         | 33.7 MB   | ############################################################################ | 100%
textacy-0.6.2        | 187 KB    | ############################################################################ | 100%
pyphen-0.9.5         | 2.7 MB    | ############################################################################ | 100%
unidecode-1.0.23     | 152 KB    | ############################################################################ | 100%
ijson-2.3            | 13 KB     | ############################################################################ | 100%
ftfy-4.4.2           | 92 KB     | ############################################################################ | 100%
cld2-cffi-0.1.4      | 5.8 MB    | ############################################################################ | 100%
pyemd-0.5.1          | 68 KB     | ############################################################################ | 100%
python-levenshtein-0 | 71 KB     | ############################################################################ | 100%
```
