### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by martijnvanbeers** [chartbeat-labs/textacy#191]
After upgrading to 0.6, I get a deprecation warning for using flesch_readability_ease, but I also get a None value in return because there's a return missing on the following line:
https://github.com/chartbeat-labs/textacy/blame/master/textacy/text_stats.py#L247

**Comment by bdewilde** [comment]
Hi @martijnvanbeers , I've fixed the bug, but: that deprecation warning is there to let you know that you should be using `text_stats.flesch_reading_ease()` instead.
