### ISSUE TITLE
textacy.Vectorizer: TypeError: __init__() got an unexpected keyword argument 'weighting'

### ISSUE THREAD

**Issue by o-P-o** [chartbeat-labs/textacy#194]
I am trying to use the textacy vectorizer, textacy.Vectorizer.  In Jupyter Notebook, I do the following:

```
import textacy
tfidf = textacy.Vectorizer(weighting='tfidf')
```

This is equivalent to what is done on the usage example on the textacy documentation, so I expect it to work, but instead I get the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-9-f008b3992bf6> in <module>()
      3 #                                               ngram_range=(1, 2))
      4 import textacy
----> 5 tfidf = textacy.Vectorizer(weighting='tfidf')
      6 tfidf.fit(X)
      7 X = tfidf.transform(X)

TypeError: __init__() got an unexpected keyword argument 'weighting'
```

I have attempted to reinstall with 

`pip install textacy`

and

`pip3 install textacy`

but the error continues to occur.

This is my envronment:

```
- **platform:** darwin
- **python:** 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)  [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
- **spacy:** 2.0.10
- **spacy_models:** ['en_core_web_lg', 'en_vectors_web_lg']
- **textacy:** 0.6.0
```

**Comment by bdewilde** [comment]
Hi @o-P-o , you're using this class using out-of-date arguments. Please see this [quickstart guide](https://chartbeat-labs.github.io/textacy/getting_started/quickstart.html#analyze-a-corpus) and the [relevant release](https://github.com/chartbeat-labs/textacy/releases/tag/0.6.0) for guidance.
