### ISSUE TITLE
'divrank' and 'bestcoverage'  not working

### ISSUE THREAD

**Issue by mukund109** [chartbeat-labs/textacy#199]
## Current Behavior
The 'rank_nodes_by_divrank' and 'rank_nodes_by_bestcoverage' functions are trying to '#replace node number by node value' by calling a dict constructor incorrectly.

## Steps to Reproduce (for bugs)
```
import textacy
import textacy.keyterms as keyterms

text = """Provide a convenient entry point and interface to one or many documents, with the core processing delegated to spaCy. Stream text, json, csv, spaCy binary"""

doc = textacy.Doc(text, lang='en')
keyterms.key_terms_from_semantic_network(doc, ranking_algo='divrank')
```

raises: 
```
ValueError: dictionary update sequence element #0 has length 10; 2 is required
```

at:
```
File "textacy/keyterms.py", line 717, in rank_nodes_by_divrank
    nodes_list = list(dict(graph.nodes()))
```

## Your Environment
- **platform:** linux
- **python:** 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
- **spacy:** 2.0.11
- **spacy_models:** ['en']
- **textacy:** 0.6.1
- **networkx:** 1.11

**Comment by mukund109** [comment]
It seems like this has been [reported before](https://github.com/chartbeat-labs/textacy/issues/131), and even though a fix was made, the networkx requirements weren't updated.

I checked and it works with networkx 2.1

So I think updating your requirement.txt might fix it, unless there is any other code left that is only compatible with networkx 1.11

**Comment by bdewilde** [comment]
Hey @mukund109 , thanks for the bug report. I just pushed a fix (I hope) to master. If it doesn't resolve your issue, please reopen and let me know!
