### ISSUE TITLE
In named_entities i am specifying include_types="DATE",am getting error like (invalid `include_types` type: \"<class 'str'>\") how to reslove this issue

### ISSUE THREAD

**Issue by SreejaRoyal** [chartbeat-labs/textacy#202]
Hi, this is my code..... in response I want only one entity type, for example ( Two weeks ago-> DATE,
One month->DATE)
>>text='''Two weeks ago, I was in Kuwait participating in an I.M.F. seminar for Arab educators.For 30 minutes, we discussed the impact of technology trends on education in the Middle East.And then an Egyptian education official raised his hand and asked if he could ask me a personal question:"I heard Donald Trump say we need to close mosques in the United States," he said with great sorrow.Is that what we want our kids'''
>>doc=textacy.Doc(text)
>>ner=textacy.extract.named_entities(doc, include_types="DATE", exclude_types=None, drop_determiners=True, min_freq=1)
>>for ne in ner:
          print(ne, ne.label_)
Iam getting error like,
->TypeError: invalid `include_types` type: "<class 'str'>"

How to resolve this issue.

- operating system:
- python version:3.5
- `spacy` version:2.0
- installed `spacy` models:[en]
- `textacy` version:0.6

**Comment by bdewilde** [comment]
Oh, wow. This is a bug, and I can't believe I missed it. For now, just putting "DATE" inside a list or tuple should make this code run. I'll push a fix to master when I have a chance.
