### ISSUE TITLE
GPL dependencies with requirements.txt

### ISSUE THREAD

**Issue by dahernan** [chartbeat-labs/textacy#203]
The following libs included on requirements are GPL
python-levenshtein  
unidecode

Is it possible to replace them with something Apache compatible?

Thanks

**Comment by bdewilde** [comment]
Hi @dahernan , thanks for your patience, it's been a busy few weeks. I was aware of the license issue for `python-levenshtein`, but not `unidecode`. I haven't seen any packages with the same functionality and more permissive licenses, but I'm very open to suggestions. Do you know of anything?

**Comment by codingatty** [comment]
Would [`text-unidecode`](https://pypi.org/project/text-unidecode/) work? Like `unidecode`, it is a port of the Perl `Text::Unidecode` library, but under the Artistic License to avoid the GPL issues of `unidecode`.

**Comment by bdewilde** [comment]
For what it's worth, I've decided to remove `unidecode` and its associated functionality from `textacy`: https://github.com/chartbeat-labs/textacy/commit/b5d372650f22feae8e2d945d2ee1b8e1aa93441f

Would still love a fast alternative to `python-levenshtein`...
