### ISSUE TITLE
Segmentation fault importing textacy

### ISSUE THREAD

**Issue by gijswobben** [chartbeat-labs/textacy#206]
I've installed textacy through conda but when I import textacy I get a segmentation fault. I've tried different ways of installing (e.g. through pip, and conda) but I keep getting the same error.

## Steps to Reproduce

```
$ conda install textacy
$ python

Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import textacy
Segmentation fault
```

## Your Environment

- operating system: Windows 7
- python version: 3.6.5
- `spacy` version: 2.0.11
- installed `spacy` models: en + nl
- `textacy` version: 0.6.2

**Comment by bdewilde** [comment]
Hi @gijswobben , is there any more output to go along with this error message? Does the package successfully install via `conda` or `pip`? Could this a problem related to Windows 7? I don't know of any way to debug this issue with the given information.

**Comment by gijswobben** [comment]
Package installs successfully through conda (no error messages, no warnings). Sadly I've copied the entire stack-trace in the "steps to reproduce" section... So no, there is no more output to go on. I've check the amount of memory (since segmentation errors usually indicate a lack of memory), but I have around 8GB of free space in RAM, so importing should work.

I just don't know how to start debugging with so little to go on. Importing spacy works fine, as soon as I try to import textacy it crashes. Does textacy provide any additional logging / debug mode? Do you know of a way to get more info?

**Comment by bdewilde** [comment]
Hi @gijswobben , just checking back on this. Did the installation issue ever get resolved? Do you know if newer versions of textacy still have this problem?

**Comment by gijswobben** [comment]
@bdewilde, No.. I stopped trying at some point
