### ISSUE TITLE
Guide to getting started to contribute

### ISSUE THREAD

**Issue by anujpahade** [chartbeat-labs/textacy#212]
Would love to start contributing to this project. Unable to find a contribution guide or an issue with some beginner friendly label. Help appreciated.

**Comment by bdewilde** [comment]
Hi @anujpahade , thanks for the offer! I've been super busy with another side-project (my upcoming wedding), so haven't had time lately to work on `textacy`. I would love some help!

There are a handful of open issues labeled "help wanted", but the most beginner-friendly would probably be #117 . Basically, it entails doing an analysis end-to-end (noting any issues with the workflow/API or bugs in the code along the way!), and writing it up in markdown or rst format so it can be added to the package docs.

Some of the other "help wanted" issues are better if you'd prefer to work on a less user-facing, more code-focused task, but that depends on your skills and preferences. Feel free to get going, or send more details to help me find you a task! 🙂 

As for a contribution guide: That's long been on my backburner. Will get to it when I've got free time again!
