### ISSUE TITLE
Issue with Numpy on Ubuntu 18.04

### ISSUE THREAD

**Issue by atuldubey007** [chartbeat-labs/textacy#216]
Getting the following error on server:

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

What should I do?

**Comment by bdewilde** [comment]
Hi @atuldubey007 , that error message describes what I would recommend trying: uninstall and then reinstall `numpy` within your dev environment. Does that resolve the error?

**Comment by atuldubey007** [comment]
The conflict was in python versions. I had integrated it with Django. However, fixing the python conflict solved my issue. Thanks for your support.
