### ISSUE TITLE
numpy.ufunc has the wrong size, try recompiling

### ISSUE THREAD

**Issue by AYEG** [chartbeat-labs/textacy#218]
Just want to put this here in case someone else receives the same errors. Somehow started getting these errors causing my flask app to crash, 

>    import textacy.keyterms 
>   File "/usr/local/lib/python3.6/site-packages/textacy/keyterms.py", line 23, in <module>
>     from . import similarity
>   File "/usr/local/lib/python3.6/site-packages/textacy/similarity.py", line 20, in <module>
>     from pyemd import emd
>   File "/usr/local/lib/python3.6/site-packages/pyemd/__init__.py", line 75, in <module>
>     from .emd import emd, emd_with_flow, emd_samples
>   File "__init__.pxd", line 885, in init pyemd.emd
> ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

I tried uninstalling and reinstalling numpy , pyemd, scikit-learn during the build which didn't help. 

A solution to this problem is to use  pip install with --no-cache-dir

**Comment by bdewilde** [comment]
Thanks for posting, plus a solution! These sorts of errors can be frustrating.
