### ISSUE TITLE
needs a version bump and submission to PyPi to make latest PRs accessable

### ISSUE THREAD

**Issue by ckot** [chartbeat-labs/textacy#221]
I uninstalled my fork which included my 2 PRs which were just merged into master, but they aren't accessible via pip install yet.  I'm able to work around via : 

`pip install git+https://chartbeat-labs/textacy`

though.  I did add a comment  to PR #220 (closed) about a possible breaking change, so perhaps this means the change *could* be made after all before you push it out to PyPi, provided you like the idea.

## Your Environment

- operating system:
- python version:
- `spacy` version:
- installed `spacy` models:
- `textacy` version:

**Comment by bdewilde** [comment]
Hey @ckot , thanks for all the PRs and issues, and pardon the delay! I've not had a chance to work on `textacy` for a couple weeks, but hope to get through most of this over the weekend. I can probably cut a minor release for you early next week.

**Comment by ckot** [comment]
No problem @bdewilde.  As I have other outstanding PRs introduced after I added this issue (and a few other changes I've been playing with), I'm still working with branches off my own fork anyway.

**Comment by bdewilde** [comment]
🎉 https://github.com/chartbeat-labs/textacy/releases/tag/0.6.3 🎉
