### ISSUE TITLE
Undefined variable in textacy.spacier.utils.merge_spans

### ISSUE THREAD

**Issue by popelucha** [chartbeat-labs/textacy#225]
variable ents is not defined

## Expected Behavior
 for start_char, end_char, label in ents: <- ents is not defined

## Possible Solution
should be doc.ents

## Your Environment

- operating system:
- python version:
- `spacy` version:
- installed `spacy` models:
- `textacy` version:

**Comment by bdewilde** [comment]
Thanks for the bug report. I _think_ it should actually be `ents` => `spans`, where `spans` is defined in the preceding line: https://github.com/chartbeat-labs/textacy/blob/master/textacy/spacier/utils.py#L97

Does that seem right to you?

**Comment by popelucha** [comment]
> Thanks for the bug report. I _think_ it should actually be `ents` => `spans`, where `spans` is defined in the preceding line: https://github.com/chartbeat-labs/textacy/blob/master/textacy/spacier/utils.py#L97
> 
> Does that seem right to you?

Absolutely, thanks for reviewing it.
