### ISSUE TITLE
Could able to import textacy package.

### ISSUE THREAD

**Issue by RamanRajarathinam** [chartbeat-labs/textacy#245]
**Workspace:**
* Linux (already installed l**ibbz2-dev**)
* Virtual env (already installed **bz2file**)
* Python 3.7

![Screenshot 2019-05-30 at 3 50 38 PM(1)](https://user-images.githubusercontent.com/16095608/58628137-98490a00-82f6-11e9-9d87-8b2c0e372b31.png)

can some of you please help me to solve this?

**Comment by bdewilde** [comment]
Whoa, that's weird — normally the standard library works without any trouble. Can you import `bz2` directly in the repl?

**Comment by RamanRajarathinam** [comment]
Hey @bdewilde , Thanks for your reply.

> Can you import bz2 directly in the repl?

The same error happens. Has it something to do with my system or python3.7 env? 
Why I am asking this is, It is working completely fine in python3.5 env.

**Comment by bdewilde** [comment]
Hi @RamanRajarathinam , I can't tell you exactly what's gone wrong, but something in your PY3.7 install is definitely off. The standard library should always work. Are you able to install a fresh version, and then import `bz2` without issue?

**Comment by RamanRajarathinam** [comment]
> Are you able to install a fresh version, and then import `bz2` without issue?

Nope. There seems to be a problem in **import bz2** itself

**Comment by bdewilde** [comment]
Hey, I have no way to debug this. `import bz2` is valid Python that should work without issue, assuming the installation is good. I did a bit of google searching and found a couple SO posts about `bz2` issues on Linux — e.g. [this](https://stackoverflow.com/questions/38630720/python-import-error-no-module-named-bz2) or [this](https://stackoverflow.com/questions/12806122/missing-python-bz2-module) — maybe they can point you in the right direction.
