### ISSUE TITLE
Installing `textacy[lang]` fails due to `cld2-cffi` bug

### ISSUE THREAD

**Issue by michelleful** [chartbeat-labs/textacy#246]
### steps to reproduce

1. `pip install cld2-cffi` or `pip install textacy[lang]`

### expected vs. actual behavior

I expect the install to conclude correctly. Instead, an error ensues ending in `cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1`

### possible solution?

Amend the documentation to suggest using the following command in case `pip install cld2-cffi/textacy[lang]` doesn't work:

`CFLAGS="-Wno-narrowing" pip install cld2-cffi`, per [a suggestion in the issues on `cld2-cffi`'s github page](https://github.com/GregBowyer/cld2-cffi/issues/12).

`CFLAGS="-Wno-narrowing" pip install textacy[lang]` should also work.

### context

Trying to use the language detection aspects of `textacy`.

### environment

- operating system: Ubuntu Linux 18.04
- python version: 3.7.0
- gcc version: 7.3.0
- `spacy` version: (not relevant)
- installed `spacy` models: (not relevant)
- `textacy` version: 0.7.0

**Comment by bdewilde** [comment]
Hi @michelleful , sorry about the hassle. Installing `cld2-cffi` has long been problematic in certain dev environments, so I recently decided to rip it out in favor of a home-brewed language classifier. See: https://github.com/chartbeat-labs/textacy/pull/247. This won't be an issue soon.

**Comment by Nivek92** [comment]
What solved the issue for me was running ```CFLAGS="-Wno-narrowing" pip3 install cld2-cffi```
as suggested in the issues of the cld2-cffi repo
hope it helps.

**Comment by bdewilde** [comment]
Hey @michelleful , I've released a new version that drops this problematic dependency: https://github.com/chartbeat-labs/textacy/releases/tag/0.7.1 . I'm going to close this issue, but please open a new one if you run into any installation or language identification-related difficulties. :)
