### ISSUE TITLE
Failure to load depechemood on Python 2.7 due to unicode vs str bug

### ISSUE THREAD

**Issue by robclewley** [chartbeat-labs/textacy#25]
In [data.py](https://github.com/chartbeat-labs/textacy/blob/42ea974ff63853a84b1ea98c80a2d771230f2e78/textacy/data.py), on py 2.7 the delimiters to `read_csv` must not be unicode literals, which they will be here due to the future import of `unicode_literals`. I patched with a wrap of those delimiters with `str()` but I'm not sure that's going to work on Python 3.

**Comment by bdewilde** [comment]
Hi @robclewley, thanks for the heads-up! How strange that Py2's `csv` module doesn't accept any unicode inputs... ¯\_(ツ)_/¯ 

I'll patch this ASAP, and some time soon will add tests for this module to make sure I catch such things in the future.
