### ISSUE TITLE
preprocess text broken

### ISSUE THREAD

**Issue by nyejon** [chartbeat-labs/textacy#250]
### steps to reproduce
Just use preprocess_text

 if normalize_unicode is True:
        text = normalize_unicode(text, form="NFC")

### expected vs. actual behavior

    text = normalize_unicode(text, form="NFC")
TypeError: 'bool' object is not callable

### possible solution?
Change the name of normalize_unicode for either the bool, or method.

- `textacy` version: 0.7.1

**Comment by bdewilde** [comment]
Oh gosh 🤦‍♂ I can't believe I missed that — and didn't test for it. Will fix ASAP.

**Comment by bdewilde** [comment]
Alright, the fix is up on `master`. This is as good a prompt as any to prioritize improving textacy's text preprocessing functionality for the next release. Thanks for the quick heads-up. :+1:
