### ISSUE TITLE
Invalid subject verb object tuple in case of a composite subject

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [chartbeat-labs/textacy#251]
### steps to reproduce

>>> doc = nlp("Aslam and Yahya are good friends.")
>>> for svo in textacy.extract.subject_verb_object_triples(doc):
...     print (svo)
... 
(Aslam, are, friends)
(Yahya, are, friends)

### environment

- operating system:
- python version:
- `spacy` version:
- installed `spacy` models:
- `textacy` version:

**Comment by bdewilde** [comment]
Hi @ZeeshanA1i , this function is pretty basic, and as you can see, doesn't work in all cases. I would love to see somebody improve it and submit a PR.

**Comment by bdewilde** [comment]
Very belated update: SVO triple extraction has been updated, and is now available in the v0.11 release: https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0
