### ISSUE TITLE
Convert all space symbols to one form

### ISSUE THREAD

**Issue by saippuakauppias** [chartbeat-labs/textacy#278]
### context
Unicode contains many space symbols: https://www.htmlsymbols.xyz/punctuation-symbols/space-symbols

### proposed solution
All space symbols need to convert to one form (default [ASCII space](https://www.htmlsymbols.xyz/unicode/U+0020))

**Comment by bdewilde** [comment]
Hi @saippuakauppias , this seems like an easy task for regular expressions. Does `re.sub(r"\s+", " ", text, flags=re.UNICODE)` work for you?

**Comment by saippuakauppias** [comment]
No, this symbols not replaced by regular expressions :)

```python
import re
test = '_\u00A0_\u2000_\u2001_\u2002_\u2003_\u2004_\u2005_\u2007_\u2008_\u2009_\u200A_\u200B_\u2060_\u3000_\uFEFF_'
print(re.sub(r"\s+", " ", test, flags=re.UNICODE))
```

> _ _ _ _ _ _ _ _ _ _ _ _​_⁠_ __

**Comment by bdewilde** [comment]
Hi @saippuakauppias , sorry about the belated reply. It looks like three of those code points don't match `r"\s+"`: `\u200B`, which is a zero-width space; `\u2060`, which is a no-break space; and `\uFEFF`, which is a zero-width no-break space. I'm pretty confident that the zero-width spaces should not be replaced by single space, and according to Wikipedia:

> U+2060 WORD JOINER (HTML &#8288; · WJ): encoded in Unicode since version 3.2. The word-joiner *does not produce any space*, and prohibits a line break at its position

So, for purposes of "normalizing whitespace", I think the thing to do here is to replace each of these three code points by an empty string, i.e.

`re.sub(r"[\u200B\u2060\uFEFF]", "", text)`

Does that seem reasonable to you?

**Comment by saippuakauppias** [comment]
Yes, I think it's good solution for this case :)
