### ISSUE TITLE
always UNICODE errors

### ISSUE THREAD

**Issue by shahmohamadi** [chartbeat-labs/textacy#282]
I can't do anything with textacy.preprocess functions. all of them give some UNICODE related error to me even simple examples like this one:

`raw_text = """ The best programs, are the ones written when the programmer is supposed to be working on something else.Mike bought the book for $50 although in Paris it will cost $30 dollars.
Don’t document the problem, fix it.This is from https://twitter.com/codewisdom?lang=en. """`

`textacy.preprocess.remove_punct(raw_text)`

<class 'tuple'>: (<class 'AttributeError'>, AttributeError("module 'textacy.constants' has no attribute 'PUNCT_TRANSLATE_UNICODE'",), <traceback object at 0x7f2957df9248>)

**Comment by bdewilde** [comment]
Hi @shahmohamadi , which version of `textacy` and Python are you using? In the latest version, `textacy.preprocess.remove_punct()` no longer exists...

**Comment by mzeidhassan** [comment]
@shahmohamadi You may want to check this URL:
https://chartbeat-labs.github.io/textacy/api_reference/text_processing.html?highlight=remove_punct#textacy.preprocessing.remove.remove_punctuation

**Comment by shahmohamadi** [comment]
@bdewilde @mzeidhassan Thank you. it fixed.
