### ISSUE TITLE
textacy.lang_utils.identify_lang throws IndexError: pop from empty list

### ISSUE THREAD

**Issue by Dabbrivia** [chartbeat-labs/textacy#291]
### steps to reproduce

1. do this
install Ubuntu LTS 18.04 on WSL Windows 10, install textacy into a virtualenv with python3
cd /mnt/c/venvs/
virtualenv -p python3 eb_ts
source /mnt/c/venvs/eb_ts/bin/activate
2. then this
run python3
>>>import textacy
>>>textacy.lang_utils.identify_lang('Was ist das denn?')

### expected vs. actual behavior
the /mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/data/lang_identifier/lang-identifier-v1.1-sklearn-v0.22.pkl.gz should be downloaded completely and the language be determined as "de"

The download seems to fail at 22%
 22%|████████████████████████▉                                                                                      | 9.00/40.0 [00:00<00:00, 402B/s]
pop from empty list
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textacy
>>> textacy.lang_utils.identify_lang('Was ist das denn?')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/lang_utils.py", line 156, in identify_lang
    lang = self.pipeline.predict(text_).item()
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/lang_utils.py", line 100, in pipeline
    self._pipeline = self._load_pipeline()
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/lang_utils.py", line 108, in _load_pipeline
    pipeline = joblib.load(f)
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 588, in load
    obj = _unpickle(fobj)
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.6/pickle.py", line 1315, in load_obj
    args = self.pop_mark()
  File "/usr/lib/python3.6/pickle.py", line 1057, in pop_mark
    self.stack = self.metastack.pop()
IndexError: pop from empty list
>>>

### context

autodetect language, it worked before

### environment

- operating system: Ubuntu LTS 18.04 on WSL Windows 10
- python version: Python 3.6.9 (default, Nov  7 2019, 10:44:02)
- `spacy` version: 2.2.1
- installed `spacy` models:
https://github.com/explosion/spacy-models/releases/download/de_core_news_md-2.2.0/de_core_news_md-2.2.0.tar.gz#egg=de_core_news_md==2.2.0
https://github.com/explosion/spacy-models/releases/download/el_core_news_md-2.2.0/el_core_news_md-2.2.0.tar.gz#egg=el_core_news_md==2.2.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.2.0/en_core_web_lg-2.2.0.tar.gz#egg=en_core_web_lg==2.2.0
https://github.com/explosion/spacy-models/releases/download/es_core_news_md-2.2.0/es_core_news_md-2.2.0.tar.gz#egg=es_core_news_md==2.2.0
https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-2.2.0/fr_core_news_md-2.2.0.tar.gz#egg=fr_core_news_md==2.2.0
https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-2.2.0/it_core_news_sm-2.2.0.tar.gz#egg=it_core_news_sm==2.2.0
https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.2.1/nl_core_news_sm-2.2.1.tar.gz#egg=nl_core_news_sm==2.2.1
https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-2.2.0/pt_core_news_sm-2.2.0.tar.gz#egg=pt_core_news_sm==2.2.0
https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-2.2.0/xx_ent_wiki_sm-2.2.0.tar.gz#egg=xx_ent_wiki_sm==2.2.0
- `textacy` version: 0.9.1

while trying to run I got this textacy.utils.print_markdown(textacy.utils.get_config())
 python
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import textacy
>>> textacy.utils.print_markdown(textacy.utils.get_config())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/utils.py", line 64, in print_markdown
    print("{}".format("\n".join(md_items)))
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/utils.py", line 62, in <genexpr>
    for k, v in items
  File "/mnt/c/venvs/eb_ts/lib/python3.6/site-packages/textacy/utils.py", line 147, in to_unicode
    raise TypeError("`s` must be {}, not {}".format((str, bytes), type(s)))
TypeError: `s` must be (<class 'str'>, <class 'bytes'>), not <class 'list'>
>>>

**Comment by bdewilde** [comment]
Hi @Dabbrivia , this issue was discussed — and probably resolved — over here: #292. So, I'm closing this issue as a duplicate.
