### ISSUE TITLE
Thank You for maintaining this library. Indirect Speech extracation

### ISSUE THREAD

**Issue by thak123** [chartbeat-labs/textacy#293]
I would like to thank you for creating and maintaining this library.
I tried to used the Gate plugin for quote extraction in News but the dependencies in GATE are outdated hence ended up using textacy.

I am interested in contributing more to the quote extraction part.

**Comment by bdewilde** [comment]
Hi @thak123 , thanks for offering to help! I've long had some relatively simple functionality for extracting _direct_ quotations (see [here](https://chartbeat-labs.github.io/textacy/build/html/api_reference/information_extraction.html#textacy.extract.direct_quotations)), but don't have anything for indirect. I'd love to improve both! How can I help you contribute?
