### ISSUE TITLE
outdated version of textacy on Anaconda

### ISSUE THREAD

**Issue by aflueckiger** [chartbeat-labs/textacy#294]
Textacy on Anaconda is outdated. In addition to the improvements in textacy, there is also the update to Python 3.8 that is not compatible with the current version of textacy (v0.8) as the following suggests:

`  - textacy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']`

Could you please update textacy on Anaconda?

Moreover, I also want to say thanks for creating and maintaining this package. It renders many corpus linguistic-related tasks very easy. Thus, I plan to introduce the package in a seminar that I teach. Certainly, there are other ways to install textacy beside Anaconda. Yet, it seems to me that installation via conda-forge is the easiest option when Anaconda is already in place.

**Comment by bdewilde** [comment]
Hi @aflueckiger , thanks for the reminder. A couple versions back, the textacy feedstock on conda-forge stopped letting me update it, reasons unknown. Since I don't use Anaconda, it's been difficult to keep up-to-date, but I'll give it another shot.

**Comment by bdewilde** [comment]
Hey, just a quick update: I've gotten the ball rolling over at https://github.com/conda-forge/textacy-feedstock/pull/26. Will let you know when we get the newer versions released on conda forge.

**Comment by aflueckiger** [comment]
Thanks a lot @bdewilde for your swift reaction.

**Comment by aflueckiger** [comment]
Hi @bdewilde, I have checked the textacy feedstock and your provisional PR. Yet, it seems that @rmax doesn't find the time. Is there another way to get it through?

**Comment by bdewilde** [comment]
hi @aflueckiger , it seems like he hasn't had the time, yes. i'll try to give it a shot when i myself have some time, but it may take me a bit. i really don't understand that whole system — i don't use conda, and i don't _like_ conda — so i'm mostly fumbling around in unfamiliar config files.

sorry about the delay. i hope this hasn't caused any issues in your seminar!

**Comment by rmax** [comment]
Sorry for the months delay! Versions `0.9.1` and `0.10.0` are up 🎉

**Comment by bdewilde** [comment]
I was on the edge of my seat, watching those builds run! 😅 THANK YOU @rmax for catching `textacy` up over on conda forge.
