### ISSUE TITLE
attribute error: textacy has no attribute 'preprocess'

### ISSUE THREAD

**Issue by Leo808s** [chartbeat-labs/textacy#297]
I created scripts last summer that called textacy preprocess - all of a sudden this stopped working a couple of days ago.

text3 = textacy.preprocess.normalize_whitespace(r"C:\Users\Desktop\hello.txt")

returns : AttributeError: module 'textacy' has no attribute 'preprocess'
 
I expected preprocess to work as it had in the past. The error is from version 0.9.0 but I've tried 1 and .7 as well. I didn't change anything else in these scripts. I went back even to the conda version I had installed originally and v 2.2.2 spacy

I have NLP pipelines that utilize spacy and textacy - normalizing whitespace is essential.
- operating system: windows 10
- python version: 3.7.3
- `spacy` version: 2.2.2 - had current, downgraded to try
- installed `spacy` models: 
- `textacy` version: .9 - tried multiple

**Comment by bdewilde** [comment]
Hi @Leo808s , that functionality changed and got moved in the 0.8.0 release: https://github.com/chartbeat-labs/textacy/releases/tag/0.8.0

Here are the docs for the current version, v0.10.0: https://chartbeat-labs.github.io/textacy/build/html/api_reference/text_processing.html
