### ISSUE TITLE
'spacy.tokens.doc.Doc' object has no attribute 'to_bag_of_terms'

### ISSUE THREAD

**Issue by Wapiti08** [chartbeat-labs/textacy#310]
### steps to reproduce

1. do this
2. then this
3. finally, this

### environment

- operating system: Win10
- python version: 3.8.1
- `spacy` version: 2.3.2
- installed `spacy` models: en-core-web-sm
- `textacy` version: 1.4.1

This is my code:
```
docx_textacy.to_bag_of_terms(ngrams=(1, 2, 3), named_entities=True, we
```

And I got this error:
```
'spacy.tokens.doc.Doc' object has no attribute 'to_bag_of_terms'
```

I have checked the [document](https://textacy.readthedocs.io/en/stable/api_reference/spacier.html?highlight=Doc). And I have no idea what's wrong with this error.

Please give me some tips on that. Thanks

**Comment by bdewilde** [comment]
Hi @Wapiti08 , I can't reproduce your error because the code example you gave is incomplete. Could you provide a full example?

As for that error message: `Doc` extensions like `to_bag_of_terms` are added when you `import textacy` (see [here](https://github.com/chartbeat-labs/textacy/blob/master/src/textacy/__init__.py#L10)). Have you done that?

**Comment by Wapiti08** [comment]
```
sentence = "The bag of words (BoW) approach works well for multiple text classification problems. This approach assumes that presence or absence of word(s) matter more than the sequence of the words. However, there are problems such as entity recognition, part of speech identification where word sequences matter as much, if not more. Conditional Random Fields (CRF) comes to the rescue here as it uses word sequences as opposed to just words."

spacy_lang = textacy.load_spacy_lang("en_core_web_sm")
docx_textacy = spacy_lang(sentence)
bot = docx_textacy.to_bag_of_terms(ngrams=(1, 2, 3), named_entities=True, weighting='count',as_strings=True)
```

Then when  I executed it, I got this:
```
'spacy.tokens.doc.Doc' object has no attribute 'to_bag_of_terms'
```

**Comment by Wapiti08** [comment]
Sorry. I found the reason. It should be like:
```
spacy_lang = textacy.load_spacy_lang("en_core_web_sm")
docx_textacy = spacy_lang(sentence)
bot = textacy.spacier.doc_extensions.to_bag_of_terms(docx_textacy, ngrams=(1, 2, 3), named_entities=True, weighting='count',as_strings=True)
```
