### ISSUE TITLE
IndexError: [E201] Span index out of range

### ISSUE THREAD

**Issue by mzeidhassan** [chartbeat-labs/textacy#314]
Hi @bdewilde,

I updated spaCy to the latest release '2.3.5', but something seems to be wrong or incompatible

Here is the error I am getting:

```
IndexError: [E201] Span index out of range.
Traceback:
File "py37/env/lib/python3.7/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "py37/env/deep_analysis.py", line 314, in <module>
    acronyms = textacy.extract.acronyms_and_definitions(doc)
File "py37/env/lib/python3.7/site-packages/textacy/extract.py", line 599, in acronyms_and_definitions
    window_ = window.text
File "span.pyx", line 503, in spacy.tokens.span.Span.text.__get__
File "span.pyx", line 190, in spacy.tokens.span.Span.__getitem__
```

## Environment
- operating system: Ubuntu 16.04
- python version: 3.7.9
- `spacy` version: 2.3.5
- installed `spacy` models: en_core_web_sm
- `textacy` version:  0.10.1

Any idea?

Thanks in advance!

**Comment by mzeidhassan** [comment]
I also would like to confirm that everything was working just fine with spaCy 2.3.2

**Comment by svlandeg** [comment]
Hi all,

As @mzeidhassan mentions, this could indeed be related to a bug in spaCy where calling `span.text` on an empty `Span` would result in an `IndexError`.

There's a few ways of dealing with this:
- Ensure you never define empty spans if you can
- Use `self.text_with_ws` as a workaround instead

**Comment by mzeidhassan** [comment]
Hi @bdewilde,
The issue is closed, but I am not sure if it resolved the issue or not. Using "text_with_ws" extracts only the acronym itself, without its full wording. Am I missing something? Can you please let me know if there is a workaround to get it right? Thanks in advance!

**Comment by mzeidhassan** [comment]
I am closing this issue, because it is fixed in the latest release of Textacy. Thanks a million for the update.
