### ISSUE TITLE
spaCy 3.0 support?

### ISSUE THREAD

**Issue by mzeidhassan** [chartbeat-labs/textacy#315]
Hi textacy team,

First, thanks for the amazing library. 

Any plans to support the new spaCy 3.0 release?

Thanks

**Comment by bdewilde** [comment]
Hey @mzeidhassan , I'm working on it — follow along in the `develop` branch, if you're curious! Please pardon the delay, the v3 release caught me at a busy time. So far, I've gotten textacy running with spacy v3, but the major changes in that library should prompt something similar in this one to match. I'll close this ticket out when there's a proper v3-compatible release.

**Comment by mzeidhassan** [comment]
Hi @bdewilde, this is the best news ever. Thanks a million! Textacy is a real gem indeed.

**Comment by bdewilde** [comment]
Update: `textacy` supports (indeed, _requires_) spaCy v3 as of today's v0.11 release: https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0
