### ISSUE TITLE
to_bag_of_terms() got an unexpected keyword argument 'ngrams'

### ISSUE THREAD

**Issue by paulakeen** [chartbeat-labs/textacy#335]
I've installed the latest version of textacy, and the code I had working in previous versions of textacy stopped working properly when it comes to extract bags of terms. I keep getting the error: 

```
    bot = doc._.to_bag_of_terms(ngrams=(1,2, 3), entities = True, weighting = "count", as_strings = True)
TypeError: to_bag_of_terms() got an unexpected keyword argument 'ngrams'
```

I've tried several times in two different OS and got the same behaviour. The code I used to test this is very simple and extracted from the documentation:
```
text = 'This is the text from a document that would have been extracted previously.'
en = textacy.load_spacy_lang("en_core_web_sm", disable=("parser",))
doc = textacy.make_spacy_doc(text, lang=en)
doc = en(text)
print(doc._.preview)
bot = doc._.to_bag_of_terms(ngrams=(1,2, 3), entities = True, weighting = "count", as_strings = True)
```

- operating system: MacOS-10, and Ubuntu 20.x
- python version: 3.8
my requirements.txt:
blis==0.7.4
cachetools==4.2.2
catalogue==2.0.4
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
cymem==2.0.5
Cython==0.29.23
cytoolz==0.11.0
decorator==4.4.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl
idna==2.10
jellyfish==0.8.2
Jinja2==3.0.1
joblib==1.0.1
MarkupSafe==2.0.1
murmurhash==1.0.5
networkx==2.5.1
numpy==1.20.3
packaging==20.9
pathy==0.5.2
pkg-resources==0.0.0
preshed==3.0.5
pydantic==1.7.4
pyparsing==2.4.7
Pyphen==0.10.0
requests==2.25.1
scikit-learn==0.24.2
scipy==1.6.3
smart-open==3.0.0
spacy==3.0.6
spacy-legacy==3.0.5
srsly==2.4.1
textacy==0.11.0
thinc==8.0.3
threadpoolctl==2.1.0
toolz==0.11.1
tqdm==4.61.0
typer==0.3.2
urllib3==1.26.4
wasabi==0.8.2

**Comment by mzeidhassan** [comment]
Hi @paulakeen , this code seems to be working fine at my end. It seems the quickstart page needs to be updated to match what exists @ [documentation](https://textacy.readthedocs.io/en/latest/api_reference/lang_doc_corpus.html?highlight=doc._.to_bag_of_terms(ngrams%3D(1%2C2%2C%203)%2C%20entities%20%3D%20True%2C%20weighting#textacy.extensions.to_bag_of_terms)

![image](https://user-images.githubusercontent.com/7589948/119700400-6947cf00-be10-11eb-830c-0f8fe95c9dd4.png)

Hope this helps.

**Comment by bdewilde** [comment]
Hi @paulakeen , @mzeidhassan is correct — the API for this method changed in the latest release, and I mistakenly failed to update it in the quickstart doc. The API reference linked to above is correct! I'll see about updating the quickstart sometime soon.
