### ISSUE TITLE
How does one pass keyword arguments to preprocessing pipelines?

### ISSUE THREAD

**Issue by gryBox** [chartbeat-labs/textacy#337]
Hi @bdewilde - Congratulations and a big thanks on the awesome  `0.11.0` release!  

### what's wrong?
It would be nice to have an example demonstrating how to pass keyword arguments to various functions in a preprocessing pipeline.  For example the `preprocessing.normalize.repeating_chars` function requires the `char` argument.    

```
preproc = preprocessing.make_pipeline(
        preprocessing.remove.html_tags,
        preprocessing.normalize.repeating_chars,
        preprocessing.normalize.quotation_marks,
        preprocessing.remove.accents
    )
```
### relevant page or section
[pipeline doc and example](https://textacy.readthedocs.io/en/latest/api_reference/preprocessing.html#textacy.preprocessing.pipeline.make_pipeline)

If you have time can you post a small example to this thread?
Thanks in advance

**Comment by bdewilde** [comment]
Hi @gryBox , I could've sworn I had an example showing this, but looks like I cut it out for simplicity's sake. The easiest way to pass args into individual preprocessors is to use [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial). For example:

```python
>>> from functools import partial
>>> from textacy import preprocessing
>>> preproc = preprocessing.make_pipeline(
...     preprocessing.remove.html_tags,
...     partial(preprocessing.normalize.repeating_chars, chars=".", maxn=3),
...     preprocessing.normalize.quotation_marks,
...     partial(preprocessing.remove.accents, fast=True),
...  )
```

I'll add a suitable example to the docs.
