### ISSUE TITLE
CLD2 outreach

### ISSUE THREAD

**Issue by GregBowyer** [chartbeat-labs/textacy#34]
Sorry for taking so long to get back to everyone about this, I have been working recently on windows and OSX builds.

Long and short, windows lacks the c header `stdint.h` which breaks a lot of compile things. This _should_ be fixed now if you want to give another go/.

Right now `1.1.3` should be a good build, if it is not give me a shout and I will see what I can do.

For `1.2` I will be altering the CFFI binding creation and attempting to build wheels for most platforms, which should solve these problems.

I will update this bug when I have a solid 1.2 wheel build ready for you

**Comment by bdewilde** [comment]
Hi @GregBowyer , thanks for reaching out, I really appreciate it! I can confirm that the `cld2-cffi` v0.1.3 plays nicely with `textacy` on Mac OS, but I don't have access to a Windows machine to test that. Maybe @grybox or @adrianR2 could give it a shot?
