### ISSUE TITLE
Failure to create corpus from Json file, TypeError issue

### ISSUE THREAD

**Issue by fatihbozdag** [chartbeat-labs/textacy#341]
Greetings,

I am trying to create a corpus with more than 2000 text files following the steps in the tutorial yet I got `TypeError`

```
records = textacy.io.read_json('E:/Learner Corpora/meta.json', mode = 'rt', lines = True)`
for x in records:
      doc = textacy.make_spacy_doc(x["text_field"], {'title': x['Native_language']})

Traceback (most recent call last):

  File "<ipython-input-44-ef07b19b0af4>", line 2, in <module>
    doc = textacy.make_spacy_doc(x["text_field"], {'title': x['Native_language']})
```

`TypeError: list indices must be integers or slices, not str`

I am not actually sure what I do wrong. Also, what is the best method to parse a huge text collection(individual text files) with metadata? Metadata section consists of almost 12 different data for each text. I have failed so far to create and parse such a corpus in Python.

Regards.

- operating system: Windows 10
- python version: 3.8.8
- `spacy` version: 3
- installed `spacy` models: 'en_core_web_sm'
- `textacy` version: 0.10.1

**Comment by fatihbozdag** [comment]
It seems like the problem was my JSON file. Fixed it. 

However, regarding the quickstart documentation, I needed to add 'en' to the doc section, or else it asks for spacy model. Thereby, I changed the code as follows. Is it due to Spacy 3? 

```
records = textacy.io.read_json(
...     "textacy/data/capitol_words/capitol-words-py3.json.gz",
...     mode="rt", lines=True)
>>> for record in records:
...     doc = textacy.make_spacy_doc((record["text"], {"title": record["title"]}), **lang = en**)
...     print(doc._.preview)
...     print("meta:", doc._.meta)
...     # do stuff...
...     break
Doc(159 tokens; "Mr. Speaker, 480,000 Federal employees are work...")
meta: {'title': 'JOIN THE SENATE AND PASS A CONTINUING RESOLUTION'}
```

**Comment by bdewilde** [comment]
Hey @fatihbozdag , naming of language models got more strict in spacy v3 (and hence textacy v0.11), I just neglected to update the quickstart docs. It's in my backlog! Apologies for the confusion.
