### ISSUE TITLE
Preprocessing/Normalization functions no longer work

### ISSUE THREAD

**Issue by happypanda5** [chartbeat-labs/textacy#342]
### steps to reproduce

!pip install textacy

import textacy
from textacy.preprocessing.normalize import normalize_hyphenated_words
from textacy.preprocessing.normalize import normalize_quotation_marks
from textacy.preprocessing.normalize import normalize_whitespace
from textacy.preprocessing.remove import remove_punctuation

### expected vs. actual behavior
      5 import textacy
----> 6 from textacy.preprocessing.normalize import normalize_hyphenated_words
      7 from textacy.preprocessing.normalize import normalize_quotation_marks
      8 from textacy.preprocessing.normalize import normalize_whitespace

**ImportError: cannot import name 'normalize_hyphenated_words' from 'textacy.preprocessing.normalize' (/usr/local/lib/python3.7/dist-packages/textacy/preprocessing/normalize.py)**

**Comment by bdewilde** [comment]
Hi @happypanda5 , the naming of these preprocessing functions changed in the latest version (v0.11), following this general pattern: `textacy.preprocessing.normalize.normalize_quotation_marks()` => `textacy.preprocessing.normalize.quotation_marks()` .

Check out the [release notes](https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0) and [API reference](https://textacy.readthedocs.io/en/latest/api_reference/preprocessing.html) for more details.
