### ISSUE TITLE
Why `normalize.hyphenated_words` is not able to reassemble all words separated by a line break?

### ISSUE THREAD

**Issue by afi1289** [chartbeat-labs/textacy#362]
### steps to reproduce
````
import textacy
import textacy.preprocessing as tprep

my_text = "The ca-\nfé “Saint-Raphaël” is loca-\nted on Côte. Das ist sehr sch-\nön, wen-\nn wir den T-\next normalizie-\nren können"

tprep.normalize.hyphenated_words(my_text)
````

### expected vs. actual behavior
Actual behavior is:
````
'The café “Saint-Raphaël” is located on Côte. Das ist sehr schön, wen-\nn wir den T-\next normalizieren können'

````
Expected behavior:
````
'The café “Saint-Raphaël” is located on Côte. Das ist sehr schön, wenn wir den Text normalizieren können'

````
### possible solution?
-
### context
I'm trying to use this function in a text preprocessing pipeline, namely in a data cleaning block.

### environment

- operating system: Windows 10 Pro 
- python version: 3.7.12
- `spacy` version: 3.4.0
- installed `spacy` models: -
- `textacy` version: 0.11.0

**Comment by bdewilde** [comment]
Hey @afi1289 , this preprocessing function uses a regex that looks for at least two letter-like characters on either side of a hyphen+whitespace, while the failing two cases in your example text include only a single letter on one side of the hyphen. This restriction _seems_ reasonable to me, but I don't know if it's a bad assumption in certain languages like German. Could you educate me on valid cases where a single letter gets split off from the remaining letters by a hyphen and a newline?

**Comment by afi1289** [comment]
> Hey @afi1289 , this preprocessing function uses a regex that looks for at least two letter-like characters on either side of a hyphen+whitespace, while the failing two cases in your example text include only a single letter on one side of the hyphen. This restriction _seems_ reasonable to me, but I don't know if it's a bad assumption in certain languages like German. Could you educate me on valid cases where a single letter gets split off from the remaining letters by a hyphen and a newline?

Hey @bdewilde Thanks a lot for your reply,
I don't think that is a bad assumption in German :) . I just wanted to understand this function. Now everything is clear!
