### ISSUE TITLE
 ERROR: Failed building wheel for pyemd during installation 

### ISSUE THREAD

**Issue by Aliktk** [chartbeat-labs/textacy#365]
### steps to reproduce

1. Install before properly
2. After window 11 installation all dependices are installed but this pyemd is not installing why?

### expected vs. actual behavior
I was installing the new version of the module. After window 11 installation all dependices are installed but this pyemd is not installing  I assuming that the pyemd wheel is not working I request an issue on that platform.

### possible solution?
remove if it's unnecessary.

### environment
install below modules.
sympy

1. pandas
2. textacy
3. scikit-learn
4. nltk
5. joblib
6. textblob
7. spacy
8. geotext
9. geopy
10. bs4
11. newspaper3k
12. wordcloud
13. numpy

- operating system: Windows 11
- python version: 3.6
- `spacy` version: 
- installed `spacy` models: Yes
- `textacy` version:  Not installing

**Comment by bdewilde** [comment]
Hi @Aliktk , I removed the `pyemd` dependency a couple years ago in v0.11 (https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0). I don't know what's going on with your system, but I don't think it's an issue with `textacy`.
