### ISSUE TITLE
Incompatible with NetworkX 3.0

### ISSUE THREAD

**Issue by LiorZippel** [chartbeat-labs/textacy#366]
### steps to reproduce

Textacy incompatible with NetworkX 3.0. In src/textacy/representations/network.py line 267 calls nx.pagerank_scipy but in the release of NetworkX 3.0 they made scipy the default method of pagerank and deprecated this method. (i.e. nx.pagerank is now equivalent to what nx.pagerank_scipy was in 2.8.8)

https://networkx.org/documentation/latest/release/migration_guide_from_2.x_to_3.0.html#switch-to-numpy-scipy-implementations-by-default-for-some-algorithms

### possible solution?
I think just replacing nx.pagerank_scipy with nx.pagerank in line 267 & 309 should fix this compatibility issue. At least here in this specific case

### context
I am using textacy in an independent project where I am calling the textrank method. I have been using networkX 3.0, and if possible I'd like to not pin it 2.8.8. When I called textrank I was thrown an "AttributeError: module 'networkx' has no attribute 'pagerank_scipy'"

**Comment by bdewilde** [comment]
Hi @LiorZippel , thanks for the heads-up! Looks like `networkx` v3 just got released a couple weeks ago, so I'll probably want to support v2 for a while longer. Should be a straightforward fix, even still. Will take care of this ASAP.

**Comment by bdewilde** [comment]
hi again! this should now be fixed in the `develop` branch; will close the ticket once properly merged into `main`

**Comment by doomlab** [comment]
@bdewilde - any update here?

**Comment by bdewilde** [comment]
hi @doomlab , i usually only merge dev into main when i'm about to publish a new release. i'm getting close; will probably pull back on ambition and just get something out sooner rather than later (like, in the next week or two), since it has been a while. thanks for your patience.

**Comment by bdewilde** [comment]
hi again, this should now be fixed in the [v0.13 release](https://github.com/chartbeat-labs/textacy/releases/tag/0.13.0). please reopen this issue if it is not.

**Comment by doomlab** [comment]
@bdewilde - thank you so much! I appreciate the quick feedback - the package is great, just was wondering which way to teach it to my students. I can always tell them to downgrade if it isn't working though, thanks!
