### ISSUE TITLE
Is the objects are available to be pickled  

### ISSUE THREAD

**Issue by nooralahzadeh** [chartbeat-labs/textacy#37]
## Context

I need to pickle the outputs like textcorpus, ...

**Comment by bdewilde** [comment]
Hi @nooralahzadeh, if you're looking to serialize the Doc and Corpus objects, you should use their `.save()` and `.load()` methods. The spacy data is converted to bytes and metadata is converted to json. I'm *pretty* sure these objects can't be pickled.
