### ISSUE TITLE
readthedocs site still has 0.11.0 documentation

### ISSUE THREAD

**Issue by muziejus** [chartbeat-labs/textacy#374]
### what's wrong?

The official docs site uses the old documentation. As a result, the quick start breaks on a 0.12.0 install, and the more detailed walkthrough is not available.

### relevant page or section

https://textacy.readthedocs.io/en/latest/changes.html

**Comment by bdewilde** [comment]
Hi @muziejus , thanks for the alert! It looks like the v0.12 version exists and is correct — [here](https://textacy.readthedocs.io/en/0.12.0) — but the "latest" build failed. I can see what's happening with that build (a known package incompatibility issue that hit tons of sphinx+readthedocs projects a year ago), and in fact I've already implemented the fix in textacy's develop branch: https://github.com/chartbeat-labs/textacy/commit/1e741fb6095f54f482d6395157d96ad492309106

I'm going to try a hotfix in the main branch to at least get the latest build up on readthedocs. In the meantime, please feel free to refer to the v0.12 docs.

**Comment by bdewilde** [comment]
Update: "latest" still refuses to build, but it should be fine once I merge in the dev branch. As a (temporary?) fix, I made the "stable" build default -- and that does indeed have the correct version of the docs. Check it out here: https://textacy.readthedocs.io
