### ISSUE TITLE
Accessing to the set of TextDoc based on the metadata in doc_term_matrix?

### ISSUE THREAD

**Issue by nooralahzadeh** [chartbeat-labs/textacy#38]
If we have different corpus and we create the TextCorpus of these corpora and we specified them regarding to their metadata like Genre or domain or author. How we can access their representation in vector space ( doc_term_matrix)

Is the order in the row of doc_term_matrix  as same as TextCorpus order get.docs with lambda helps us to cath them? 
Do you have any implemented similarity measure to compare these corpora? If not I would be happy to contribute and pull some new functionalities !

**Comment by bdewilde** [comment]
Hi @nooralahzadeh, you can convert a `TextCorpus` (called `corpus` below) into a document-term matrix like so:

```
>>> doc_term_matrix, id2term = corpus.as_doc_term_matrix(
...     (doc.as_terms_list(words=True, ngrams=False, named_entities=True)
...      for doc in corpus),
...     weighting='tfidf', normalize=True, smooth_idf=True, min_df=2, max_df=0.95)
```

The row index in the matrix is the same as the corpus index, which is also assigned to docs with the `Doc.corpus_index` attribute.

There's a top-level module called `distance.py` that has a variety of distance metrics, which can be easily converted into similarity metrics. Looks like it's not in the official docs — my bad.

One last comment: I'm nearing the end of a somewhat large refactor, and after merging, some of the things I wrote above will no longer be true. For example, I converted the distance metrics into similarity metrics to facilitate upcoming work on document clustering. Just a heads-up.
