### ISSUE TITLE
backports.lzma dependency in textacy

### ISSUE THREAD

**Issue by gryBox** [chartbeat-labs/textacy#40]
Hi @bdewilde - Once again I am having trouble installing textacy, and once again it is a Windows issue.
` Failed building wheel for backports.lzma`

Generating this error

![image](https://cloud.githubusercontent.com/assets/16763201/17647163/160d5f8c-61ac-11e6-9b5a-3bcbea01529a.png)

Any suggestions?

FYI: The issue installing textacy with `cld2-cffi` has been resolved, about 2 weeks ago(fix made by @GregBowyer )

**Comment by bdewilde** [comment]
Hi @gryBox, you're my canary in the Windows coal mine... sorry! A couple questions:

1. Have you looked at the backports.lzma repo ([here](https://github.com/peterjc/backports.lzma)) for issues and/or installation instructions?
1. Which version of Python are you using?

If you're using Python 3, you can actually just remove the dependency from `requirements.txt` and `setup.py` — it's only needed because I'm trying to maintain compatibility with Python 2.

**Comment by gryBox** [comment]
Hey @bdewilde 

> you're my canary in the Windows coal mine... sorry! 

np. You know how highly I think of `textacy` .  

> If you're using Python 3, you can actually just remove the dependency from requirements.txt and setup.py — it's only needed because I'm trying to maintain compatibility with Python 2.

As I hoped, after reading it's purpose on git and the name :) 

This may be the package that breaks cross-platform and language compatibility for`textacy`.  The instructions for `backports.lzma` concerning windows are opaque - And the readme explicitly states that windows is untested.  It does not install without errors on my Windows 7 python 3.5 (Anaconda) 

Let me know what you think - I would love to install and (more importantly) update textacy at some pace close to your major releases.

**Comment by bdewilde** [comment]
Hey @gryBox, since you're using python 3.5 (woot), I recommend removing `backports.lzma` from `setup.py` and `requirements.txt`, then installing via `$ python setup.py install`. A band-aid, for sure, but it ought to unblock you.

Meanwhile, I'll ping the package author on an existing issue (https://github.com/peterjc/backports.lzma/issues/14) and see what I can do. If we can't get `backports.lzma` to work on Windows, I'll just drop it. Python 2 users won't be able to use lzma compression, but that's not a deal-breaker like this installation problem.

Sorry again about the occasional WIndows hiccups... I'm doing better about not accidentally breaking Py2 compatibility, but dammit I have no idea what to do about Windows. Let me know if you have any ideas. :)

**Comment by gryBox** [comment]
>  I have no idea what to do about Windows. Let me know if you have any ideas

My two cents regarding windows is conda. In short that means that I have never had a package fail installing from conda using `conda install package` or `conda update package`.

 I don't know all the particulars of how it works, (yet), but there is are different channels ([here](http://conda.pydata.org/docs/custom-channels.html)) for different builds - Although that seems tedious.  

There is a good tutorial for making `conda packages` [conda build](http://conda.pydata.org/docs/building/build.html).  Let me know if you want me to explore it further.  I am not sure how well it integrates with your builds.  The other possible upside to to making textacy a conda build is it might give textacy more exposure (if you want it)

**Comment by bdewilde** [comment]
Hi @gryBox, thanks for the suggestion and links. I tried conda a couple times, but never warmed up to it. It looks like I need to have conda installed to follow the directions for `conda build`, and I'm not sure how that'll affect my `pyenv`-powered environment. So... I'm going to hold off on this. Before releasing v0.3 (coming in the next few days), I will either learn how to get `backports.lzma` working on Windows, or drop it and lzma compression for Py2 users. Not a very satisfying solution, but it'll work.

Btw, have you seen [this fascinating Twitter thread](https://twitter.com/jakevdp/status/765308397050695680) going on today? Very relevant.

**Comment by gryBox** [comment]
@bdewilde  - Your solution will work.  Do you have any interest in **me** mucking around with a conda build?  I can't promise anything in terms of results (this would be my first time), but it might free up some of your time for 'funner 'textacy' things'

Let me know either way

> have you seen this fascinating Twitter thread going on today? Very relevant.
There is so much to learn

**Comment by bdewilde** [comment]
@gryBox — Far be it for me to turn down free help! :) Yes, absolutely, if you have the time, please muck around with conda and let me know how it goes, either here on this issue (which I'll close when the `backports.lzma` issue is resolved) or as a PR. :pray: Thanks in advance!

**Comment by bdewilde** [comment]
By the way, I just came across [Appveyor](https://packaging.python.org/appveyor/); it may be a long-term solution. Will do some digging of my own!

**Comment by gryBox** [comment]
Nice find!  Appveyor

**Comment by GregBowyer** [comment]
FWIW Appveyor is what I use to get cld2-cffi builds on windows

I am also considering the manylinux and wheel support using these
services.

On Tue, Aug 16, 2016, at 12:07 PM, gryBox wrote:
> Nice find!  Appveyor
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/chartbeat-labs/textacy/issues/40#issuecomment-240205557

**Comment by GregBowyer** [comment]
https://github.com/GregBowyer/cld2-cffi/commit/88644f87bcd5adfe0bd65e02b138d0f598c9431e might be of interest tyo you.

Be ready to do a bunch of remote desktop in windows its a bit gross


On Tue, Aug 16, 2016, at 02:07 PM, Greg Bowyer wrote:
> FWIW Appveyor is what I use to get cld2-cffi builds on windows
>
> I am also considering the manylinux and wheel support using these
> services.
>
> On Tue, Aug 16, 2016, at 12:07 PM, gryBox wrote:
>> Nice find!  Appveyor
>> — You are receiving this because you were mentioned. Reply to this
>> email directly, view it on GitHub[1], or mute the thread[2].
>>
>


Links:

  1. https://github.com/chartbeat-labs/textacy/issues/40#issuecomment-240205557

**Comment by bdewilde** [comment]
HUP: I got Appveyor working for `textacy`, and will include Windows-specific wheels in the next (v0.3) release. This may or may not resolve the issue with `backports.lzma`... but, it seems like a good thing. Thanks to both of you for your feedback!

**Comment by gryBox** [comment]
@bdewilde Nice! Was is it painful? In any case let me know when I can do a pull and so it can be tested in windows.

**Comment by gryBox** [comment]
@bdewilde  How appropriate? [feather and Appveyor](https://github.com/wesm/feather/issues/215)

**Comment by gryBox** [comment]
Can I test v0.3 for windows?

Itay Livni

**Comment by bdewilde** [comment]
Hey @gryBox, feel free to check out the current `master` and test it out — I'm planning to officially release it tomorrow, complete with Windows wheels from Appveyor up on PyPi. (Let me know if something doesn't work!)

**Comment by gryBox** [comment]
Ok... It will be a bit later.

I ran your suggested fix yesterday for the first time got a missing `spacy
en library`.  Easy enough to install-  but was wondering if this was
because I ran it with  cld2-cffi for the first time?

Itay Livni

**Comment by gryBox** [comment]
@bdewilde :) Really nice. `textacy` installs out of the box in Windows 7 ... I wish you could see my silly grin.
