### ISSUE TITLE
keyterms function extract function parameters

### ISSUE THREAD

**Issue by patcollis34** [chartbeat-labs/textacy#44]
I saw you guys changed good_pos_tags to include_tags in most functions. You forgot to do it in the sgrrank function

**Comment by bdewilde** [comment]
Hey @patcollis34 , thanks for pointing this out! It's a very easy fix, but it also revealed that I don't yet have any tests for the keyterms extraction module. 😧 

I've been on a brief development hiatus to finish up another all-consuming side project, but look forward to resuming work in October. Looks like I'll start with tests!
