### ISSUE TITLE
cachetools 2.0.0 breaks textacy

### ISSUE THREAD

**Issue by gramonov** [chartbeat-labs/textacy#45]
Great tool! I noticed that `cachetools==2.0.0` introduced breaking changes and `textacy` won't work anymore.

```python
import textacy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/textacy/__init__.py", line 16, in <module>
    from textacy import data, preprocess, text_utils
  File "/usr/local/lib/python2.7/site-packages/textacy/data.py", line 20, in <module>
    from cachetools import cached, Cache, hashkey
ImportError: cannot import name hashkey
```

As a quick solution, consider fixing `cachetools` version in the *requirements.txt*.

Thanks,

**Comment by bdewilde** [comment]
Thanks for the HUP, @gramonov . Looks like `cachetools` recently published a release with breaking changes. I'll pin the version in `requirements.txt` tomorrow, sorry about the hassle.

**Comment by bdewilde** [comment]
I'm actually just updating the requirements to the latest version — turned out to be a trivial fix. Thanks again for letting me know.
