### ISSUE TITLE
SGRank issue

### ISSUE THREAD

**Issue by nsankar** [chartbeat-labs/textacy#47]
Hi , 

SGRank API seems to have some issue when I tried.. I believe there was a recent bug fix.  when would this get updated?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by bdewilde** [comment]
Hey @nsankar, I can't troubleshoot your issue without more information.

An issue was submitted (see #44) about an incorrect parameter name in the `sgrank` function; I pushed the fix into master. Until I release another version, which might be another month or so on account of other projects, you would have to upgrade your version to the master branch to get the fix.

If this doesn't resolve your issue, please re-open and let me know what's wrong.
