### ISSUE TITLE
can not load wikipedia files one the disk

### ISSUE THREAD

**Issue by baisk** [chartbeat-labs/textacy#51]
I try to stream wikipedia pages from files on the disk, and an error occurred.
here is my code, basically same as sample code.

    import textacy
    from textacy.corpora.wiki_reader import WikiReader
    import sys
    reload(sys)
    sys.setdefaultencoding('utf-8')

    wr = WikiReader('enwiki-20161020-pages-articles1.xml-p000000010p000030302.bz2')

    for record in wr.records(min_len=100, limit=100):
        pass

and i got this:
![image](https://cloud.githubusercontent.com/assets/2310450/19943701/8bc67234-a173-11e6-86bb-dbeaa73f7b47.png)

## Possible Solution

![image](https://cloud.githubusercontent.com/assets/2310450/19943788/f260fce4-a173-11e6-8cb6-0b9f94b764d5.png)

I guess in some wikipedia pages, 'ref' tag can be found in some section,  but can not be removed, because it's not a section itself. like this: this page always raise an error
![image](https://cloud.githubusercontent.com/assets/2310450/19943956/ae478f86-a174-11e6-97ac-c729384ac012.png)

## Your Environment

* `textacy` and `spacy` versions: textacy (0.3.1) spacy (1.1.2)
* Python version: 2.7
* Operating system and version: mac

**Comment by bdewilde** [comment]
Hey @baisk , thanks for reporting this. I dug a bit but couldn't find a clear-cut reason for this exception, but am happy to apply band-aids so you can use it. Will ping you when there's a fix out.

**Comment by bdewilde** [comment]
Hi @baisk, sorry about the delay. I've released [a new version](https://github.com/chartbeat-labs/textacy/releases/tag/0.3.2) of `textacy`, and I believe it fixes the bug you've reported here. I'm going to close the issue, but don't hesitate to re-open it if I've missed something.

**Comment by baisk** [comment]
thx for noticing. I do appreciate that.
