### ISSUE TITLE
inconsistency in handling lemmas/raw-text between corpus.word_doc_freqs and sgrank

### ISSUE THREAD

**Issue by jeremybmerrill** [chartbeat-labs/textacy#53]
There appears to be an inconsistency in how the IDF dict returned by corpus.word_doc_freqs handles lemmatization/stopwords and how SGRank handles it. 

## Expected Behavior
calls to `textacy.keyterms.sgrank(doc, idf=my_idf)` should not raise KeyError 

## Current Behavior
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/204434/.pyenv/versions/3.5.1/lib/python3.5/site-packages/textacy/keyterms.py", line 80, in sgrank
    for term, count in term_counts.items()}
  File "/Users/204434/.pyenv/versions/3.5.1/lib/python3.5/site-packages/textacy/keyterms.py", line 80, in <dictcomp>
    for term, count in term_counts.items()}
KeyError: 'be'
````

## Possible Solution
I don't have quite enough understanding of how the textacy ecosystem should work, or how SGRank should work, to really know what the solution might be, but I *think* the problem has something to do with lemmatization or stopwords.

I have only seen that KeyError appear when one of the normalized tokens (with `normalized_str`, I think) in `doc` is either very common word ("be", "go") or hard-to-tokenize strings like `PERCENT"-` or `ET`. 

My suspicion, having just starting playing with Textacy (which seems awesome and to have great promise, so, thank you!) is that the `word_doc_freqs` method eliminates stop words or garbage or acronyms or something like that.

The problematic tokens vary based on whether I generate my IDF dict with `lemmatize=True` or `lemmatize=False`. It seems almost as if `sgrank` sometimes expects the keys in the IDF dict to be lemmatized and other times not.

## Steps to Reproduce (for bugs)
````
import textacy
import spacy
import csv
nlp = spacy.load('en')
tweets = []
with open('some_tweets.csv') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        tweets.append(row['body'])
corpus = textacy.corpus.Corpus('en', tweets)
doc = corpus[0]
my_idf = corpus.word_doc_freqs(lemmatize=True, weighting='idf', lowercase=True, as_strings=True)
textacy.keyterms.sgrank(doc, idf=my_idf)
````
At this point, depending on the content of `doc`, you should see a `KeyError` on line 80 of `keyterms.py`, complaining that some token from `doc` isn't in my_idf.

## Context
Just trying to minimally test out SGRank, along with a few other key-term extraction algorithms.

## Your Environment
spacy (1.3.0)
textacy (0.3.2)
Python 3.5.1

**Comment by bdewilde** [comment]
Hey @jeremybmerrill , thanks for pinging me on this. Somebody actually submitted this very issue _via email_ last week, so I'm glad to have it visible here for all to see. In short, some functions use `textacy.spacy_utils.normalized_str()` internally to get normalized string representations for tokens and/or spans, and that function does a smart check to leave proper nouns and acronyms as-is and lemmatize everything else. As you've noticed, this is can lead to inconsistencies with a function that produces a mapping where keys are always lemmatized strings.

I'm working on a fix that resolves the hard-coded mismatching between token normalizations across all functions, and not just the example here. The WIP is in this branch: https://github.com/chartbeat-labs/textacy/tree/token-normalization As a bonus, I also improved the `sgrank()` function a bit. I'm hoping to have this merged into master in the next few days, but feel free to check it out before then.

**Comment by jeremybmerrill** [comment]
Hi @bdewilde,

Whoa, awesome. I'll check out that branch. Thanks!

**Comment by jeremybmerrill** [comment]
I definitely am seeing the improved SGRank, so thank you! And _some_ of the cases no longer end up with KeyError. (The `PERCENT"-` and `ET` cases, specifically)

I am, however, still seeing trouble with cases where tokens are getting lemmatized, specifically `'m` getting lemmatized to `be`. The IDF dict still has an entry for `'m` while SGRank is looking for `be` (and not finding it, causing a KeyError).

Thanks again for your hard work on this library and I look forward to continuing to experiment with it. :) Happy to share my corpus privately if it's useful, though it sounds like you've already got a handle on the bug.

**Comment by bdewilde** [comment]
Thanks for following up... I should probably catch those key errors so the function doesn't crash on unexpected strings. Will ping you again once I've finished updating token normalization on the `Corpus` class, which _should_ resolve your error.

**Comment by jeremybmerrill** [comment]
Cool, thank you!

**Comment by bdewilde** [comment]
Hey @jeremybmerrill , I've updated everything that needs updating for you to run `sgrank()` without it crashing on you. Changes are still in the `token-normalization` branch because I'd like to add some tests before merging, but figured I'd give you a HUP.

**Comment by jeremybmerrill** [comment]
Thanks, checkin' it out!

**Comment by jeremybmerrill** [comment]
Works great. Thanks! 

It seems that SGRank excludes proper nouns. Is that intentional or, like, a side-effect of how the algorithm (which I'll admit to not having explored in depth) works?

**Comment by bdewilde** [comment]
@jeremybmerrill Great catch! That's a bug — fortunately, trivial to fix. I submitted a bug to spacy a few months back because proper nouns were always tagged as regular nouns, which has since been fixed. So now I have bugs arising from assumptions about the old tagging behavior. Will fix ASAP, add some tests, then get this merged into master. Thanks a ton for digging in.

**Comment by jeremybmerrill** [comment]
Oh man, don't thank me, thank you! I seem to have a zillion 90%-baked implementations of basic NLP stuff in different scripts, so Textacy will at least save me a ton of time in not having to implement and bugfix those ever again. All the stuff I hadn't played with yet (like SGRank) coming for free is a huge bonus.
