### ISSUE TITLE
Unable to reproduce example in README

### ISSUE THREAD

**Issue by lifan0127** [chartbeat-labs/textacy#55]
Attempt to reproduce the code example in README led to very different result after the 2nd code block. Instead of obtaining a doc_term_matrix with over 11k terms, mine only has 9 terms.

## Steps to Reproduce (for bugs)
```py
import textacy

cw = textacy.corpora.CapitolWords()
docs = cw.records(speaker_name={'Hillary Clinton', 'Barack Obama'})

content_stream, metadata_stream = textacy.fileio.split_record_fields(docs, 'text')
corpus = textacy.Corpus('en', texts=content_stream, metadatas=metadata_stream)

corpus  
# Corpus(1241 docs; 859235 tokens)
```
```py
doc_term_matrix, id2term = textacy.vsm.doc_term_matrix(
  (doc.to_terms_list(ngrams=1, named_entities=True, as_strings=True) for doc in corpus),
  weighting='tfidf', normalize=True, smooth_idf=True, min_df=2, max_df=0.95
)

print(repr(doc_term_matrix))  
# <1238x9 sparse matrix of type '<class 'numpy.float64'>'
#	with 540 stored elements in Compressed Sparse Row format>
```

## Your Environment

* `textacy` and `spacy` versions: textacy=0.3.2, spacy=1.3.0
* Python version: 3.5
* Operating system and version: Windows 7

**Comment by lifan0127** [comment]
It appears lemmatize is causing the problem in doc.to_term_list() method. If lemmatize is set to False, I get all the terms in dtm as expected:

```py
doc_term_matrix, id2term = textacy.vsm.doc_term_matrix(
  (doc.to_terms_list(ngrams=1, lemmatize=False, named_entities=True, as_strings=True) for doc in corpus),
  weighting='tfidf', normalize=True, smooth_idf=True, min_df=2, max_df=0.95
)

print(repr(doc_term_matrix))
# <1241x13711 sparse matrix of type '<class 'numpy.float64'>'
#	with 223404 stored elements in Compressed Sparse Row format>
```

**Comment by bdewilde** [comment]
Hey @lifan0127 , thanks for the report. I exactly copied the code you posted using the same versions of textacy and spacy, and got a different (expected) result:

```
In [7]: corpus
Out[7]: Corpus(1241 docs; 857296 tokens)
In [8]: doc_term_matrix, id2term = textacy.vsm.doc_term_matrix(
   ...:   (doc.to_terms_list(ngrams=1, named_entities=True, as_strings=True) for doc in corpus),
   ...:   weighting='tfidf', normalize=True, smooth_idf=True, min_df=2, max_df=0.95
   ...: )
In [9]: print(repr(doc_term_matrix))
<1241x11357 sparse matrix of type '<class 'numpy.float64'>'
	with 211387 stored elements in Compressed Sparse Row format>
```

I'm running this on macOS and don't have access to Windows, but I can't imagine the difference in OS would cause this sort of difference. Is it possible that you don't have the spaCy language data installed in your env? If so, then I'm honestly not sure how to debug, since I can't reproduce.

**Comment by lifan0127** [comment]
After moving to 64 bit Python and downloading all spaCy data, I am able to reproduce the example now. Thanks so much!
