### ISSUE TITLE
Unexpected behavior of to_bag_of_terms method

### ISSUE THREAD

**Issue by covuworie** [chartbeat-labs/textacy#57]
I've been playing around with the latest version of this great library Textacy! However, the [to_bag_of_terms](http://textacy.readthedocs.io/en/latest/_modules/textacy/doc.html#Doc.to_bag_of_terms) method is not behaving as I expected. I'm not sure if this is a bug or if I am not using the API as I should be.

## Expected Behavior

I see that the documentation indicates that the parameters ('lowercase' and 'lemmatize') have been deprecated and the parameter ('normalize') seems to have replaced these. I expected to receive a deprecation warning message when setting the 'lowercase' or 'lemmatize' parameters. When setting the 'normalize' parameter to the following values I expected:

- 'lemma' => lemmatization only
- 'lower'   => lowercasing only
- callable  => 'to_bag_of_terms' method to return the output from the callable

## Current Behavior

When setting the deprecated parameters ('lowercase' and 'lemmatize') I do not receive any deprecation warning message. However, when setting the 'normalize' parameter to the following values I get:

- 'lemma' => both lowercasing and lemmatization
- 'lower'   => both lowercasing and lemmatization
- callable  => both lowercasing and lemmatization

## Possible Solution

- A deprecation warning message when 'lowercase' or 'lemmatize' parameters are set.
- Honoring the behavior of the callable when 'normalize' is set to it, or alternatively providing an explanation in the documentation of what the callable is meant to do.
- If the code is correct then maybe instead explaining how I can accomplish the task explained in the Context section would suffice. 

## Steps to Reproduce (for bugs)

I think this should be fairly easy for you to reproduce, but I have code I can share with you if necessary. However, maybe an explanation is all that is required. 

## Context

I was trying to provide my own implementation to filter specific key phrases (terms) in a doc/corpus. 

## Your Environment

* `textacy 0.3.2` and `spacy 1.4.0` versions:
* Python version: 3.5.2
* Operating system and version: Windows 7

**Comment by bdewilde** [comment]
Hi @covuworie , you're describing some recent changes to string normalization that are currently in the master branch on github but have not yet been released — `textacy` v0.3.2 does not have them. So, if you're using v0.3.2 as you wrote, then you wouldn't see the deprecation messages and changed behavior.

If, instead, you're using the latest version in master, then maybe there's a bug, but I don't see it.  That said, I think you've misinterpreted what passing a callable in for the `normalize` param does: it operates on a per-token or per-span basis, converting the objects into a string representation as desired. So, maybe you want all terms uppercased rather than lowercased, or you want to stem them rather than lemmatize.

Let me know if you're using v0.3.2 or the latest in master, and if what I wrote above clarifies your expectations.

**Comment by covuworie** [comment]
Hi @bdewilde, thanks very much for the prompt and clear explanation. I was using the `textacy 0.3.2` release. I checked the latest code of [doc](https://github.com/chartbeat-labs/textacy/blob/master/textacy/doc.py) in master and can see the deprecation messages. 

I do not think I misinterpreted the purpose of passing a callable to the `normalize` param. I read the spaCy documentation for [Span](https://spacy.io/docs/api/span) which says it's a slice from a Doc object. My docs just happen to be very small and the Span is in fact the whole document! As you said, I expected to be able to use the callable to convert the Span (i.e. the whole Doc) into the string representation I desired. I guess this is what line 489 in [doc](https://github.com/chartbeat-labs/textacy/blob/master/textacy/doc.py) in master is meant to do? Does `textacy 0.3.2` have the same line of code or is it only in master?

**Comment by bdewilde** [comment]
Hey @covuworie , glad we sorted that out — sorry about the confusion! v0.3.2 doesn't let you pass in a callable to the `normalize` param (which doesn't exist anyway, I suppose), so unless you want to switch to the master branch on github, you're stuck with `lemmatize=True` or `lowercase=True`, for now. I'll put out a new `textacy` release as soon as I have a bit more to include, hopefully by end of January. I've been sidetracked doing PRs on someone else's open-source project... :)

Is there still an unresolved issue, or can I close this out?

**Comment by covuworie** [comment]
Hey @bdewilde, great - thanks very much for the clarification. I can switch to the master branch for the time-being whilst waiting for the new release. Feel free to close this one out! I'll let you know if I spot anything else. Also, I may have some enhancement ideas further down the line. Once again, great library!

**Comment by bdewilde** [comment]
Sounds good. I'm open to feature requests — and PRs! :)
