### ISSUE TITLE
Empty string key term can be returned by textrank

### ISSUE THREAD

**Issue by mlehl88** [chartbeat-labs/textacy#58]
Due to an [issue in spaCy](https://github.com/explosion/spaCy/issues/719), textrank can return the empty string as a key term for a document. This is due to spaCy sometimes lemmatizing the string 's' into the empty string, which is not filtered out by the textrank implementation.

## Expected Behavior and Possible Solution
Textacy should filter out any empty strings as key terms.

## Steps to Reproduce (for bugs)
```
>>> from spacy.en import English
>>> import textacy
>>> 
>>> nlp = English()
>>> 
>>> s = """hobby maker show s...
...        figures: sakurai twins s..."""
>>> 
>>> doc = nlp(s)
>>> textacy.keyterms.textrank(doc, n_keyterms=3)
[('maker', 0.19939773459751794), ('sakurai', 0.19939773459751794), ('', 0.19085869422866814)]
```

## Environment
* `textacy` and `spacy` versions: Textacy 0.3.2 with Spacy 1.5
* Python version: 3.6
* Operating system and version: Mac OS X Version 10.10.5

**Comment by bdewilde** [comment]
Hey @mlehl88 , thanks for the HUP! I saw your issue in spaCy's repo and was wondering if that might show up downstream in textacy... 😩  Will fix!

**Comment by bdewilde** [comment]
Okay! A simple fix is pushed in master.
