### ISSUE TITLE
New version to PyPI

### ISSUE THREAD

**Issue by hetsch** [chartbeat-labs/textacy#59]
Thank you for this nice package. I've seen that you changed some code in `keyterms.sgrank` and friends. What about baking and uploading a new version to PyPI? Thank you!

**Comment by bdewilde** [comment]
Hey @hetsch , thanks for the ping. I've not had time to do anything with textacy for a couple months, having gone down a rabbit hole refactoring someone else's OSS package. BUT I'm almost done. I'd hoped to make a few additional improvements to textacy before putting out another version, but how about I time-box it: I'll commit to publishing a new version on pypi within the next two weeks, regardless of additional development. Sound good?

**Comment by hetsch** [comment]
@bdewilde Perfect, that makes totally sense. Good luck with the other project, not to envy ... :)

**Comment by bdewilde** [comment]
@hetsch I didn't get to add much more, but did fix a couple extra bugs before this release: https://github.com/chartbeat-labs/textacy/releases/tag/0.3.3 

Thanks for waiting. :)
