### ISSUE TITLE
Acronyms_and_definitions returns only 1st character of definition when passing in known defs

### ISSUE THREAD

**Issue by dawazualex** [chartbeat-labs/textacy#61]
When passing in a list of known definitions to the acronyms_and_definitions function, the dict object that is returned only returns the 1st character of the corresponding definition.

## Expected Behavior
Return the full definition for the acronym

## Current Behavior
Returns only the 1st character of the definition

## Possible Solution
Looks to stem around line 452 in extract.py.  Doing a defs[0] instead returns the confidence and empty definition for acronyms w/o definitions and just the definition w/o confidence for found expansions.

## Steps to Reproduce (for bugs)
1. `extract.acronyms_and_definitions(doc1, known_acro_defs= {'OSH':'OUTSIDE HOSPITAL', "IBS":"IRRITABLE BOWEL SYNDROME"})`

## Context
There are a lot of acronyms in the medical space and this feature will be very helpful.

## Your Environment

* `textacy` and `spacy` versions: 0.3.3 & 1.6.0
* Python version: 3.5 64bit
* Operating system and version: Windows 7 64bit

**Comment by bdewilde** [comment]
Hey @dawazualex , thanks for the heads-up! I was able to reproduce the bug, and will get a fix out soon.
