### ISSUE TITLE
Textacy is Apache-licensed, but has a dependency on fuzzywuzzy, a GPL lib

### ISSUE THREAD

**Issue by samshah** [chartbeat-labs/textacy#63]
Hi,

Currently, Textacy is [Apache licensed](https://github.com/chartbeat-labs/textacy/blob/2f1eb45fe18109f10e609bc106669c153313aa65/LICENSE.txt), but it has a [dependency on fuzzywuzzy](https://github.com/chartbeat-labs/textacy/blob/9c5930b1513643febc2d08eb4fff20d28d116787/setup.py#L14), which is a [GPL library](https://github.com/seatgeek/fuzzywuzzy/blob/2df7b4310175d45c1f2c0d31f015866b01540fed/LICENSE.txt). This basically precludes using textacy in many environments due to the viral nature of GPL (it effectively makes textacy GPL). Replacing fuzzywuzzy seems straightforward if Textacy intends to be Apache-licensed.

**Comment by bdewilde** [comment]
Hi @samshah , don't know if you and @matthayes know each other, but you posted the same issue as him at essentially the same time. :) Since I responded to his (see Issue #62) first, please comment there if you have anything to add. I'm going to close this one out.
