### ISSUE TITLE
Problem on to_terms_list method on readme

### ISSUE THREAD

**Issue by fer-git** [chartbeat-labs/textacy#66]
I tried to follow the example on the readme, but I got incorrect result.

```
import textacy

cw = textacy.corpora.CapitolWords()
docs = cw.records(speaker_name={'Hillary Clinton', 'Barack Obama'})
content_stream, metadata_stream = textacy.fileio.split_record_fields(
        docs, "text")
corpus = textacy.Corpus(u'en', texts=content_stream, metadatas=metadata_stream)
doc = corpus[-1]
terms = doc.to_terms_list(ngrams=1, named_entities=True, as_strings=True)
print(list(terms))
```
The result that I got is list of empty strings.

I play around with the arguments on to_terms_list, and I got it right if I set 'normalize' to be False.
```
terms = doc.to_terms_list(ngrams=1, named_entities=True, as_strings=True, normalize=False)
```
Perhaps you need to update the readme.

## Your Environment
* textacy version: 0.3.3
* Python version: 2.7.10
* Operating system and version: Mac OSX 10.11.6

**Comment by bdewilde** [comment]
Hi @fer-git , I was unable to reproduce your issue. I copy-pasted your code snippet, ran it in Python 2.7.10, textacy 0.3.3, on the latest macOS, and got the following:

```
...
>>> print(list(terms))
[u'senate', u'my 8 year', u'senate', u'american', u'10 year ago', u'new york', u'new yorkers', ...]
```

If you don't specify `normalize=False`, then the default behavior is to lemmatize. Can you use `spacy` to lemmatize terms outside of the context of this function?

**Comment by fer-git** [comment]
I did further testing, it looks like the reason is that I have not downloaded the language model.
So, I ran
```
python -m spacy.en.download all
```
Now the script output above is the same as the output stated in readme.

**Comment by bdewilde** [comment]
Great, thanks for the heads-up! I've been meaning to clarify the need for installing spacy and its model data for a while — will definitely add that to the documentation soon.
