### ISSUE TITLE
Installation section of documentation needs dependency on spacy data added

### ISSUE THREAD

**Issue by covuworie** [chartbeat-labs/textacy#68]
## Current Behavior
The method `textacy.keyterms.sgrank` silently fails by returning an empty list and the method `textacy.keyterms.textrank` crashes with an index out of range exception on line 70 of [network.py](https://github.com/chartbeat-labs/textacy/blob/master/textacy/network.py) when the spacy English data is not installed. I haven't checked any other methods.

## Expected Behavior
Exceptions should be thrown for methods relying on part-of-speech (POS) tagging when the spacy English data is not installed and the code certainly should not crash.

## Possible Solution
The installation section of the documentation needs to explain that the command `python -m spacy.en.download all` needs to be run to download the spacy English data in order for any methods using part-of-speech (POS) tagging to work. I just fell foul of the [Empty lemma and zero POS](https://github.com/explosion/spaCy/issues/174) issue.

Exceptions should be thrown by these methods, although I am not sure how difficult it is for you to detect the existence of the spacy English data installation. If it's too difficult to detect, then I tell you that I prefer the crash to the silent fail! It was the crash which enabled me to actually figure out what was going on by just looking at the code. 

## Your Environment

* `textacy 0.3.3` and `spacy 1.6.0` versions:
* Python version: 3.6.0.1
* Operating system and version: Windows 7

**Comment by bdewilde** [comment]
Hey @covuworie , sorry about the trouble. I very recently added a note about this to the installation instructions — see [this commit](https://github.com/chartbeat-labs/textacy/commit/61bbd2627b8119e9fa5252b1881bae956e65a57d) — but that change has not yet been propagated to the [official docs site](http://textacy.readthedocs.io/). Do you think that's enough? If not, what more would you like to see there?

I'm not sure if / how I can detect the presence of spacy data or not from Python, but I'll look into it. Pull requests welcome, of course!

**Comment by covuworie** [comment]
Thanks for the quick response @bdewilde. It's great that you are already ahead of the game and have updated the docs. The only change I would make is to explicitly link to the [Download models](https://spacy.io/docs/usage/#models) section as the webpage is already quite long. I'm sure this change will fix a lot of the occurrences of this issue so it's probably sufficient.

I see that the spacy user can download the language models to a custom location which makes this is a difficult one. Possibly the only solution is for spacy to be updated to provide a method to get the path to the language model data. This could possibly be checked when a textacy and/or spacy doc is created. A warning message could then possibly be issued to tell the user that POS tagging is disabled. If spacy hasn't addressed the issue yet then I certainly don't think textacy should!

**Comment by bdewilde** [comment]
Believe it or not, I ran afoul of this problem and submitted an issue to spacy about it last fall: https://github.com/explosion/spaCy/issues/578

I don't think they ever added a warning message for when a user tries to, say, POS tag a text without having the language data, but ideally that would come from them. I'll see if I can hack something into textacy though.

**Comment by covuworie** [comment]
Thanks for taking the time to look at this @bdewilde - very much appreciated! As I said, the warning is probably the best solution. But alas it looks like they didn't add it, closed out the issue and moved on.

**Comment by bdewilde** [comment]
Btw, it looks like there will be some useful functionality in the impending `spacy` release that should make checking model info feasible. For example, [`spacy.cli.info.py`](https://github.com/explosion/spaCy/blob/ec3e8106620ef80b848dcb4664a99f4c0dfdc073/spacy/cli/info.py). Something to keep an eye on...

**Comment by covuworie** [comment]
Looks good!
