### ISSUE TITLE
SGRank method crashes at "low" values of term co-occurence window size

### ISSUE THREAD

**Issue by covuworie** [chartbeat-labs/textacy#72]
## Current Behavior
Using the `keyterms.sgrank` method with the default window size of 1500 is intractable when using a corpus of several thousands of documents (and even hundreds) due to performance issues. I wish the authors of the SGRank paper had mentioned this.

Reducing the window_size to smaller values (e.g. using 1/10 of the default value or lower) drastically speeds up the performance. However at these "low" values of window_size a divide by zero crash occurs with the following stack trace:

```python

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-56-be9b3fa36a41> in <module>()
    113 
    114 doc = Doc(text)
--> 115 keyphrases = keyterms.sgrank(doc, normalize=u'lemma', window_width=15, n_keyterms=20, idf=None)
    116 print(keyphrases)

C:\WinPython\WinPython-64bit-3.6.0.1Qt5\python-3.6.0.amd64\lib\site-packages\textacy\keyterms.py in sgrank(doc, normalize, window_width, n_keyterms, idf)
    147         sum_edge_weights = sum(t2s.values())
    148         norm_edge_weights.extend((t1, t2, {'weight': weight / sum_edge_weights})
--> 149                                  for t2, weight in t2s.items())
    150 
    151     # build the weighted directed graph from edges, rank nodes by pagerank

C:\WinPython\WinPython-64bit-3.6.0.1Qt5\python-3.6.0.amd64\lib\site-packages\textacy\keyterms.py in <genexpr>(.0)
    147         sum_edge_weights = sum(t2s.values())
    148         norm_edge_weights.extend((t1, t2, {'weight': weight / sum_edge_weights})
--> 149                                  for t2, weight in t2s.items())
    150 
    151     # build the weighted directed graph from edges, rank nodes by pagerank

ZeroDivisionError: float division by zero

```

Note that I am also able to set a negative window_size and the algorithm silently succeeds due to the code on line 60 of [keyterms.py](https://github.com/chartbeat-labs/textacy/blob/master/textacy/keyterms.py). I'm guessing window_size must be >=2.

## Possible Solution
I read the SGRank paper a few days and thought I understood most of it, but obviously not enough to know what is actually wrong with the code! :) (sum_logdists or one or more term weights are zero, but I don't know why). For the second issue it should be easy enough to raise a ValueError when window_size < 2. 

## Steps to Reproduce 
The following code crashes with a divide by zero error for all values of window_size <= 15:

```python

from textacy import Doc, keyterms

# The Rime of The Ancient Mariner 
text = """
Hear the rime of the ancient mariner
See his eye as he stops one of three
Mesmerizes one of the wedding guests
Stay here and listen to the nightmares of the sea.

And the music plays on, as the bride passes by
Caught by his spell and the mariner tells his tale.

Driven south to the land of the snow and ice
To a place where nobody's been
Through the snow fog flies on the albatross
Hailed in God's name, hoping good luck it brings.

And the ship sails on, back to the North
Through the fog and ice and the albatross follows on.

The mariner kills the bird of good omen
His shipmates cry against what he's done
But when the fog clears, they justify him
And make themselves a part of the crime.

Sailing on and on and north across the sea
Sailing on and on and north 'til all is calm.

The albatross begins with its vengeance
A terrible curse a thirst has begun
His shipmates blame bad luck on the mariner
About his neck, the dead bird is hung.

And the curse goes on and on at sea
And the curse goes on and on for them and me.

"Day after day, day after day,
we stuck nor breath nor motion
as idle as a painted ship upon a painted ocean
Water, water everywhere and
all the boards did shrink
Water, water everywhere nor any drop to drink."

There calls the mariner
There comes a ship over the line
BUt how can she sail with no wind in her sails and no tide.

See...onward she comes
Onward she nears out of the sun
See, she has no crew
She has no life, wait but here's two.

Death and she Life in Death,
They throw their dice for the crew
She wins the mariner and he belongs to her now.
Then, crew one by one
they drop down dead, two hundred men
She, she, Life in Death.
She lets him live, her chosen one.

"One after one by the star dogged moon,
too quick for groan or sigh
each turned his face with a ghastly pang
and cursed me with his eye
four times fifty living men
(and I heard nor sigh nor groan)
with heavy thump, a lifeless lump,
they dropped down one by one."

The curse it lives on in their eyes
The mariner wished he'd die
Along with the sea creatures
But they lived on, so did he.

and by the light of the moon
He prays for their beauty not doom
With heart he blesses them
God's creatures all of them too.

Then the spell starts to break
The albatross falls from his neck
Sinks down like lead into the sea
Then down in falls comes the rain.

Hear the groans of the long dead seamen
See them stir and they start to rise
Bodies lifted by good spirits
None of them speak and they're lifeless in their eyes

And revenge is still sought, penance starts again
Cast into a trance and the nightmare carries on.

Now the curse is finally lifted
And the mariner sights his home
spirits go fromhe long dead bodies
Form their own light and the mariner's left alone.

And then a boat came sailing towards him
It was a joy he could not believe
The pilot's boat, his son and the hermit,
Penance of life will fall onto him.

And the ship sinks like lead into the sea
And the hermit shrives the mariner of his sins.

The mariner's bound to tell of his story
To tell this tale wherever he goes
To teach God's word by his own example
That we must love all things that God made.

And the wedding guest's a sad and wiser man
And the tale goes on and on and on.
"""

doc = Doc(text)
keyphrases = keyterms.sgrank(doc, normalize=u'lemma', window_width=15, n_keyterms=20, idf=None)

```

## Your Environment

* `textacy 0.3.3` and `spacy 1.6.0` versions:
* Python version: 3.6.0
* Operating system and version: Windows 7

**Comment by bdewilde** [comment]
Hi @covuworie , thanks for the detailed issue report.

To your first point: I added a note to the docstring mentioning that larger values of `window_width` can dramatically increase runtime. Unfortunately, that's a feature of the algorithm and not a bug. One of these days I'll bite the bullet and cythonize chunks of textacy to improve performance, but I'm worried about getting swamped by install/compatibility problems for different dev environments.

Secondly: I added a check, so `window_width` must now be >= 2.

Third: As it turns out, you've found a legit but clearly bad edge case in the calculation. With a `window_width` of 15, the words "tide" and "sun" co-occur exactly once, with a difference in position of 15. The calculation of edge weights includes `log(window_width / pos_diff)`, which in this case equals 0. And, here's the kicker: There are no other valid candidate terms that co-occur with "tide", so the sum of all edge weights for "tide" is still exactly 0. Hence, `ZeroDivisionError`. If you were to use `window_width = 16`, there is no error! The good news is that this situation is rare but, again, clearly bad. I think what I'll do is add 1 to all weights, as we do when "smoothing" document frequencies in tf-idf calculations, to avoid the divide-by-zero problem.

**Comment by covuworie** [comment]
Hi @bdewilde, thanks very much for the fix. It's very much appreciated! The code changes look good and I even pulled the latest code and tested with thousands of docs and your changes got through each and every one of them. Sounds like a very interesting edge case - makes complete sense once you explained it! It actually took me quite some time to reproduce the problem consistently in an isolated manner, but I got there in the end. I didn't want to swamp you with a large corpus.
