### ISSUE TITLE
preprocess_text Error: object of type 'float' has no len()

### ISSUE THREAD

**Issue by ddofer** [chartbeat-labs/textacy#73]
I'm using TextAcy to preprocess text from a (UTF-8?) dataset of questions, (Quora Kaggle challenge dataset). 
[Data: http://qim.ec.quoracdn.net/quora_duplicate_questions.tsv ] 

I'm getting errors with using the preprocessing. 
The described column is a list of strings, e.g.:
`df['question2'].values[0:2]`

> ['What is the step by step guide to invest in share market?',
       'What would happen if the Indian government stole the Kohinoor (Koh-i-Noor) diamond back?']

## Expected Behavior
df["clean_question2"] = df['question2'].apply(lambda x: textacy.preprocess.preprocess_text(x, fix_unicode=True, lowercase=False, transliterate=True, no_urls=True, no_emails=True, no_phone_numbers=True, no_numbers=True, no_currency_symbols=True, no_punct=True, no_contractions=True))

(Note, this worked on another text column). 

## Current Behavior

```
df["clean_question2"] = df['question2'].apply(lambda x: textacy.preprocess.preprocess_text(x, fix_unicode=True, lowercase=False, transliterate=True, no_urls=True, no_emails=True, no_phone_numbers=True, no_numbers=True, no_currency_symbols=True, no_punct=True, no_contractions=True))

/Users/danofer/anaconda/lib/python3.6/site-packages/textacy/preprocess.py in preprocess_text(text, fix_unicode, lowercase, transliterate, no_urls, no_emails, no_phone_numbers, no_numbers, no_currency_symbols, no_punct, no_contractions, no_accents)
    197     """
    198     if fix_unicode is True:
--> 199         text = fix_bad_unicode(text, normalization='NFC')
    200     if transliterate is True:
    201         text = transliterate_unicode(text)

/Users/danofer/anaconda/lib/python3.6/site-packages/textacy/preprocess.py in fix_bad_unicode(text, normalization)
     38         str
     39     """
---> 40     return fix_text(text, normalization=normalization)
     41 
     42 

/Users/danofer/anaconda/lib/python3.6/site-packages/ftfy/__init__.py in fix_text(text, fix_entities, remove_terminal_escapes, fix_encoding, fix_latin_ligatures, fix_character_width, uncurl_quotes, fix_line_breaks, fix_surrogates, remove_control_chars, remove_bom, normalization, max_decode_length)
    152     out = []
    153     pos = 0
--> 154     while pos < len(text):
    155         textbreak = text.find('\n', pos) + 1
    156         fix_encoding_this_time = fix_encoding

TypeError: object of type 'float' has no len()
```

## Your Environment

* `textacy` and `spacy` versions: latest versions from pip
* Python version: 3.6 , anaconda
* Operating system and version: OSX Sierra 10.12.3

**Comment by ddofer** [comment]
The problematic row in question has a NaN. (I ran over chunks of the 400k file to track it :))

Suggested fix?

**Comment by bdewilde** [comment]
Hi @ddofer , I was just looking to see if something like that was the problem — glad you found it. After loading the data, I can see that the column's dtype isn't `str` but `object`, indicating the presence of null or at least not-string values. I recommend filtering out all rows with null values before applying the function, since `preprocess_text` only accepts unicode: 

```
>>> df = pd.read_csv('/Users/burtondewilde/Downloads/quora_duplicate_questions.tsv', sep='\t')
>>> print(df.shape)
(404290, 6)
>>> df = df.dropna(subset=['question2'])
>>> print(df.shape)
(404288, 6)
>>> df['clean_question2'] = df['question2'].apply(lambda x: textacy.preprocess.preprocess_text(x, fix_unicode=True, lowercase=False, transliterate=True, no_urls=True, no_emails=True, no_phone_numbers=True, no_numbers=True, no_currency_symbols=True, no_punct=True, no_contractions=True))
>>> df['clean_question2'].head()
0    What is the step by step guide to invest in sh...
1    What would happen if the Indian government sto...
2    How can Internet speed be increased by hacking...
3    Find the remainder when mathNUMBERNUMBERmath i...
4               Which fish would survive in salt water
Name: clean_question2, dtype: object
```

Looks like there are two rows with null values in that column... 🤔  I'm going to close this issue, but don't hesitate to comment if I've missed something.

**Comment by ddofer** [comment]
Another solution is df.fillna(""). 
Thanks!
