### ISSUE TITLE
Returning empty list using Textacy sgrank automated keyterm retrieval

### ISSUE THREAD

**Issue by GodotIsWaitingToo** [chartbeat-labs/textacy#76]
I am trying to extract a key term list from a document using the sgrank function in textacy, but am getting an empty list returned.

## Expected Behavior
Returns list of key terms.

## Current Behavior
Empty list returned.

## Steps to Reproduce (for bugs)
`import textacy

doc = textacy.Doc("If you are looking for a ransom, I can tell you I don't have any money!")

sgrank = textacy.keyterms.sgrank(doc, normalize=u'lemma', window_width=1, n_keyterms=10, idf=None)

print(sgrank)`

## Your Environment

* `textacy` and `spacy` versions: latest
* Python version: 3.6.1
* Operating system and version: MacOS Sierra 10.12.3

**Comment by bdewilde** [comment]
Hi @GodotIsWaitingToo , SGRank uses co-occurrence counts to rank terms, but with `window_width = 1`, there can be no co-occurrences! In fact, the algorithm's default value is 1500, and the minimum valid value is 2; recently I added that sanity check into the function, I've just not published a release with it yet:

```
In [1]: import textacy

In [2]: doc = textacy.Doc("If you are looking for a ransom, I can tell you I don't have any money!")

In [3]: textacy.keyterms.sgrank(doc, normalize=u'lemma', window_width=1, n_keyterms=10, idf=None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-9ddad16e47b6> in <module>()
----> 1 textacy.keyterms.sgrank(doc, normalize=u'lemma', window_width=1, n_keyterms=10, idf=None)

/Users/burtondewilde/chartbeat/github/textacy/textacy/keyterms.py in sgrank(doc, ngrams, normalize, window_width, n_keyterms, idf)
     65         n_keyterms = int(round(n_toks * n_keyterms))
     66     if window_width < 2:
---> 67         raise ValueError('`window_width` must be >= 2')
     68     window_width = min(n_toks, window_width)
     69     min_term_freq = min(n_toks // 1000, 4)

ValueError: `window_width` must be >= 2

In [4]: textacy.keyterms.sgrank(doc, normalize=u'lemma', window_width=100, n_keyterms=10, idf=None)
Out[4]: [('money', 0.649122638064138), ('ransom', 0.3508773619358619)]
```

I'm not sure if the text you sent is representative of your data or just a simple example, but I should note that, as far as I know, SGRank isn't particularly suited to extracting keyterms from very short texts.

**Comment by GodotIsWaitingToo** [comment]
Hi Burton,

Thanks for the reply - the text isn't representative, I'm going to be applying the sgrank to patents and scientific literature, but just wanted to create a super simple doc for the example.

I'm still experiencing a problem, even using the code you've added above. I wonder whether it's to do with my installation. I installed textacy using pip install yesterday. Do I need to upgrade, or should it work fine?

Thanks!

**Comment by bdewilde** [comment]
Hi @GodotIsWaitingToo , in your original message you said you're using the latest versions of both textacy and spacy — so, 0.3.3 and 1.7.3, respectively? What's the problem you're experiencing? Could you provide code to reproduce it (or does your original code still apply)?

`textacy` v0.3.3 doesn't include the check for `window_width >= 2`, and regardless, you should still choose a sensible value for that parameter. Have you downloaded the language models needed for spacy to tag, parse, etc. a text? ([See here](https://spacy.io/docs/usage/models).) If not, then I wouldn't expect any tokens to pass the POS-tag requirement imposed by SGRank, which would give you 0 candidate terms and, of course, 0 key terms.

**Comment by GodotIsWaitingToo** [comment]
Hi Burton - my mistake, I hadn't installed spacy's English language model. I'm now getting the same output as your code snippet above. Thank you!

**Comment by bdewilde** [comment]
Good, glad it was an easy fix. 🙂  I recently updated the installation instructions in the readme to mention the models specifically, but will try to add a bit more, and will push that information to the official docs site when I next publish a release.
