### ISSUE TITLE
Question about the use of pagerank algorithm

### ISSUE THREAD

**Issue by marine9357** [chartbeat-labs/textacy#78]
I have a question about the use of the pagerank_scipy function to compute the score at the end.
I thought pagerank was not taking edge weight into account ? How does it do that here since you don't even add any parameter to the function call ?
Thank you !

**Comment by bdewilde** [comment]
Hi @marine9357 , the `networkx.pagerank_scipy()` function takes a `weight` parameter with default value "weight"; it specifies the edge data key to use as a weight. You can see just a few lines up from where I call that function, I've set edge data to be a dictionary with "weight" as its only key and a normalized edge weight as its value. So, these weight values are indeed used when computing the nodes' page ranks. It would probably be safer to make that parameter explicit — will add it to my to-do list.
