### ISSUE TITLE
probably user error maybe readability_stats() error

### ISSUE THREAD

**Issue by gryBox** [chartbeat-labs/textacy#8]
Hi - There may be an issue with the `readabilty_stats()` function it is returning:
`object of type 'generator' has no len()` from line `---> 35     n_words = len(words)`

I originally thought it might be the text that I a using, it has many number format variations  e.g `...binary "10"....66-bit transmission character...`.  However I then copy pasted your example and received the same error.

Below is the code copied from a jupyter notebook - Let me know if you want me to try anything out

```python
import textacy
```

### textacy numbers bug (maybe)

```python
text = '''Hell, it's about time someone told about my friend EPICAC. After all, he cost the taxpayers $776,434,927.54. They have a right to know about him, picking up a check like that. EPICAC got a big send off in the papers when Dr. Ormand von Kleigstadt designed him for the Government people. Since then, there hasn't been a peep about him -- not a peep. It isn't any military secret about what happened to EPICAC, although the Brass has been acting as though it were. The story is embarrassing, that's all. After all that money, EPICAC didn't work out the way he was supposed to.
And that's another thing: I want to vindicate EPICAC. Maybe he didn't do what the Brass wanted him to, but that doesn't mean he wasn't noble and great and brilliant. He was all of those things. The best friend I ever had, God rest his soul.
You can call him a machine if you want to. He looked like a machine, but he was a whole lot less like a machine than plenty of people I could name. That's why he fizzled as far as the Brass was concerned..'''

text_model = textacy.texts.TextDoc(text.strip(), lang='en')
```

#### Number of words

```python
text_model.n_words
```

    203

#### Error

```python
len(text_model.words)
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-6-247336a43fbc> in <module>()
    ----> 1 len(text_model.words)
    

    TypeError: object of type 'method' has no len()

```python
text_model.readability_stats()
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-44-e8fbedb4cd27> in <module>()
    ----> 1 text_model.readability_stats()
    

    C:\Anaconda3\lib\site-packages\textacy-0.2.0-py3.5.egg\textacy\texts.py in readability_stats(self)
        546     @property
        547     def readability_stats(self):
    --> 548         return text_stats.readability_stats(self)
        549 
        550 
    

    C:\Anaconda3\lib\site-packages\textacy-0.2.0-py3.5.egg\textacy\text_stats.py in readability_stats(doc)
         33 
         34     words = doc.words(filter_punct=True, filter_stops=False, filter_nums=False)
    ---> 35     n_words = len(words)
         36     n_unique_words = len({word.lower for word in words})
         37     n_chars = sum(len(word) for word in words)
    

    TypeError: object of type 'generator' has no len()

btw: `textacy` is very fun to use (and usefull).  `pandas` for nlp

**Comment by bdewilde** [comment]
Hey @gryBox, thanks very much for reporting this. It looks to be a bug introduced when I changed `TextDoc.words()` to be a generator function — indeed, generator objects have no `len()`. I'll push a fix ASAP. I take "pandas for nlp" as a huge compliment, so thank you! 😀
