### ISSUE TITLE
readability_stats cannot process original SpaCy Doc since doc.lang is not set in spacy.Doc (it's actually doc.vocab.lang)

### ISSUE THREAD

**Issue by woltob** [chartbeat-labs/textacy#80]
On passing an original *SpaCy* doc to readability_stats from textacy.text_stats, it cannot process the doc since it's expecting the doc.lang attribute to be set. However, spacy docs don't have this attribute. It's in doc.vocab.lang.

## Expected Behavior
Return the readability_stats from given spacy doc

## Current Behavior
Cannot find attribute doc.lang in spacy doc since it is in doc.vocab.lang

## Possible Solution
```
Checking for spacy doc. 
if instance of original spacyDoc:
     check for doc.vocab.lang != 'en'
else:
     check for doc.lang != 'en'
```

## Steps to Reproduce (for bugs)
```
from textacy.text_stats import readability_stats
import spacy
nlp = spacy('en') 
doc = nlp('Some english text with beautifully verbal verbs and silly adjectives')
print(readability_stats(doc))

<ipython-input-12-53b8f79415fc> in <module>()
print(readability_stats(doc))

/Users/{USERNAME}/anaconda/lib/python3.5/site-packages/textacy/text_stats.py in readability_stats(doc)
     27         NotImplementedError: if ``doc`` is not English language. sorry.
     28     """
---> 29     if doc.lang != 'en':
     30         raise NotImplementedError('non-English NLP is not ready yet, sorry')
     31 

AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'lang'
```

## Context
I was trying to use readability_stats from the package textacy.text_stats

* `textacy` and `spacy` versions: textacy 0.3.3, spacy 1.7.3
* Python version: 3.5 anaconda
* Operating system and version: mac ox x 10.10.5

Thanks for fixing it!

**Comment by bdewilde** [comment]
Hi @woltob , thanks for the report. This is actually expected behavior: as specified in the function's documentation, `doc` should be a `textacy.Doc`. 🙂  But, as you note, it's totally straightforward to make this work for spacy docs as well. Since I already have to make some changes to this module to accommodate languages other than English, I will add this change in at the same time.

**Comment by woltob** [comment]
Alright, thank you for the quick reply. Keep up the good work!
