### ISSUE TITLE
No  input text in textacy.doc.Doc when written to file and read from file

### ISSUE THREAD

**Issue by gryBox** [chartbeat-labs/textacy#83]
It's actually not as drastic as the title suggests.  Here goes:

I have  a `networkx ` node attribute containing a `textacy.doc.Doc`.  When the file is written using `write_gpickle`, no errors.  When the file is read back `read_gpickle` the `textacy.doc.Doc` exists just not the text inside i.e `>>> {1: Doc(0 tokens; "")}`

Should there be a warning at some level in one of the libraries? 

### Reproducible example

```
import networkx as nx
import textacy

# Make textacy doc
textacy_doc = textacy.doc.Doc('This is a string', lang='en')
textacy_doc
>>> Doc(4 tokens; "This is a string")


# Make Graph
G = nx.Graph()
G.add_node(1, textacy_doc=textacy_doc)

# Write Graph
nx.write_gpickle(G, 'G_with_textacy attribute.gpickle')

# Read Graph
G = nx.read_gpickle('G_with_textacy attribute.gpickle')
nx.get_node_attributes(G, 'textacy_doc')
>>> {1: Doc(0 tokens; "")}


```

**Comment by bdewilde** [comment]
Hi @gryBox , that is an odd result, for sure. Unfortunately, I can't replicate it:

```
import networkx as nx
import textacy

doc = textacy.Doc('This is a text.')
G = nx.Graph()
G.add_node(1, textacy_doc=doc)
nx.write_gpickle(G, '/Users/burtondewilde/Desktop/G_with_textacy_doc.gpickle')
G = nx.read_gpickle('/Users/burtondewilde/Desktop/G_with_textacy_doc.gpickle')
nx.get_node_attributes(G, 'textacy_doc')
```

results in `PicklingError: Can't pickle <function BaseDefaults.<lambda> at 0x10c2e4bf8>: attribute lookup BaseDefaults.<lambda> on spacy.language failed`.

What versions of everything are you using? (_Pretty sure_ that's in the issue template...) For me:
`textacy`: v0.3.3
`spacy`: v1.7.5
`networkx`: v1.11
`python`: v3.6

In the short term, it would probably be easiest to just include the document's text and perhaps metadata as node attributes. I know that the `spacy` folks are going to be updating how parsed documents get serialized / unserialized, but I don't know if that will help in this situation.

**Comment by gryBox** [comment]
> it would probably be easiest to just include the document's text and perhaps metadata as node attributes

Yeah.  That is what I did.  I t looks like I need to upgrade some packages `textacy` and `python`

BTW: This is the project I have been meaning to talk about with you. [learning map](https://github.com/gryBox/learning_map)
