### ISSUE TITLE
AttributeError: module 'textacy.text_stats' has no attribute 'TextStats'

### ISSUE THREAD

**Issue by oxbits** [chartbeat-labs/textacy#84]
'''
AttributeError: module 'textacy.text_stats' has no attribute 'TextStats'
'''

FYI: When I pip install or download Pypi tar.gz I get a version of text_stats.py without TextStats.

I can download latest master from github and it works.

Thank you!

**Comment by bdewilde** [comment]
Hi @oxbits , I've not yet published a new release to PyPi that includes the updates to `text_stats.py` you've seen in the master branch. Will push a release soon-ish, I've just been trying to add something more substantial before doing so.

**Comment by oxbits** [comment]
I understand.  The reason I thought it might be worth an issue was that you have the new feature in the README coupled with the suggested install approach, along with the fact that the version number is the same as the one in pip/Pypi.

I am really digging the library, thanks for the great code!

**Comment by bdewilde** [comment]
Hey @oxbits, sorry about the confusion. The docs on textacy.readthedocs.io are still in the old version, since they correspond to the most recent release, but I can see how master could get confused. I'll try to find out if/how other projects make the difference more clear.
