### ISSUE TITLE
make cld2-cffi dependency optional

### ISSUE THREAD

**Issue by henridwyer** [chartbeat-labs/textacy#85]
Installing cld2-cffi is complicated and can require root access (to install libffi).

This makes installing textacy sometimes difficult or impossible to install! But cld2 provides such a minor part of the textacy functionality, that more often than not isn't even used (when working with text most of the time you know what the language is). 

For some examples issues, see: #5

It would be great to be able to easily install textacy without this dependency, and make it optional.

**Comment by bdewilde** [comment]
Hey @henridwyer , I hear you on difficulties getting `cld2-cffi` to install. I ran into this issue just yesterday when trying to build documentation on readthedocs' servers...

I've looked multiple times for qualified replacements — `langid`, `langdetect`, etc. — but haven't found one that is 1. fast 2. accurate and 3. maintained. I will see about making the dependency requirement optional, as I've done for matplotlib.

**Comment by henridwyer** [comment]
I also briefly searched for a good replacement but couldn't find anything that seemed good enough.

I made a simple change to make the dependency optional, and return None for the language. I couldn't find anywhere where this would cause issues, but perhaps I missed something.

**Comment by bdewilde** [comment]
Hey, yeah, I saw that. Fast work! :) I will probably merge as-is then make a couple tweaks — that function should raise an exception rather than return None, but there's no need for you to worry about the nitty-gritty.
