### ISSUE TITLE
Float division by zero (ZeroDivisionError) for flesch_kincaid_grade_level having n_words = 0

### ISSUE THREAD

**Issue by woltob** [chartbeat-labs/textacy#88]
Got a division by zero exception while calculating some readability measures

1 generated an exception: float division by zero
Traceback (most recent call last):
  File "/home/devbox07/anaconda3/lib/python3.6/site-packages/textacy/text_stats.py", line 160, in readability_stats
    return {'flesch_kincaid_grade_level': self.flesch_kincaid_grade_level,
  File "/home/devbox07/anaconda3/lib/python3.6/site-packages/textacy/text_stats.py", line 110, in flesch_kincaid_grade_level
    return flesch_kincaid_grade_level(self.n_syllables, self.n_words, self.n_sents)
  File "/home/devbox07/anaconda3/lib/python3.6/site-packages/textacy/text_stats.py", line 226, in flesch_kincaid_grade_level
    return (11.8 * n_syllables / n_words) + (0.39 * n_words / n_sents) - 15.59
ZeroDivisionError: float division by zero

## Solution
Check for n_words < 1 and return a default value for flesch_kincaid_grade_level

## Context
Trying to calculate readability measures from (textacy initialized with SpaCy doc) SpaCy docs.

## My Environment
{'python': '3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]', 'platform': 'linux', 'textacy': '0.3.4', 'spacy': '1.8.0', 'spacy_models': ['en', 'en_glove_cc_300_1m_vectors-1.0.0', 'en-1.1.0']}

**Comment by bdewilde** [comment]
Hey @woltob , I'm not sure I agree that this is a problem. If the number of words in a document is 0, then such readability measures don't make sense. I think it's safer to raise an exception than to silently substitute in a default value, but maybe I'm not appreciating your use case. Could you explain what you're trying to do, and why catching an exception is less desirable than handling a default value?

**Comment by woltob** [comment]
Hi @bdewilde , 

I guess an error, or much better, a warning, can be raised, but it shouldn't be a ZeroDivisionError from the actual calculation of one method while other methods (readability measures) not dividing by 0 return some numbers. Perhaps, the wrapping method readability_stats could return None or have every value set to 0.0 in a default dictionary. 

I'm processing a lot of text and solved this issue by wrapping everything in a method and return a default dict() with 0-values of all the readability measures if the SpaCy doc is None or the len(doc.text) == 0 since I don't want to deal with None values for some documents. If 0.0 as a readability measure for null text makes sense (which I'm assuming) for all the different measures, a default value would make sense I guess.

Best,
@woltob
