### ISSUE TITLE
Flexibility to load spaCy from different data directory

### ISSUE THREAD

**Issue by bawongfai** [chartbeat-labs/textacy#9]
@bdewilde It would be good if one can specify data directory for spaCy.

textacy/texts.py
`spacy_pipeline = data.load_spacy_pipeline(lang=self.lang, data_dir='/path/to/data_dir')`

Reference:
https://github.com/spacy-io/spaCy/issues/303

**Comment by bdewilde** [comment]
Hi @bawongfai, thanks for the ping. I've been meaning to update this for a while, but have been waiting for spaCy's API to stabilize / get documented. [This](https://spacy.io/docs#english-init), for example, is relatively new.

As is, you can pass kwargs into `data.load_spacy_pipeline()` that are passed on to `spacy.en.English()` initialization — does the code you wrote _not_ work?

**Comment by henningpeters** [comment]
Btw: the API around `spacy.load()` is the future, is already pretty much stabilized and will also get properly documented soon. Not a strict guarantee that nothing will change of course, but that's the path forward as we currently see it.

**Comment by bdewilde** [comment]
@henningpeters Good to know! I figured that was the case but wasn't sure, and I've been holding off on updating this in `textacy` until I saw the official spaCy docs. Thank you for peeking in on my Issues page!! 😀

**Comment by bdewilde** [comment]
@bawongfai: I'd just like to confirm, does `spacy_pipeline = data.load_spacy_pipeline(lang=self.lang, data_dir='/path/to/data_dir')` _not_ work for you? You should be able to pass any keyword args into that function that you could normally pass into the `spacy.en.English` init, but maybe I've missed something.

(I'll be updating to spaCy's new `spacy.load()` feature sometime soon.)
