### ISSUE TITLE
Warning for readability when num sentences < 30

### ISSUE THREAD

**Issue by sixhobbits** [chartbeat-labs/textacy#92]
When you calculate the readability stats for many short pieces of text, many warnings can be raised regarding the SMOG stat (for all texts with fewer than 30 sentences).

## Expected Behavior

Either the warning should be disabled, or there should be an easy way to suppress it.

## Current Behavior

`WARNING:root:SMOG score may be unreliable for n_sents < 30` is shown many times if readability stats are calculated in a loop.

## Possible Solution
Can we remove the warning altogether? I assume that none of the readability stats are reliable for < 30 sentences. Why is this error raised for SMOG?

## Steps to Reproduce (for bugs)

1.
1.
1.

## Context

I'm calculating readability statistics for many texts. I'm not even using the SMOG stat, but I get hundreds of warnings for the short texts

## Your Environment

```
{'platform': 'darwin',
 'python': '3.6.0 (default, Dec 24 2016, 00:01:50) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]',
 'spacy': '1.8.0',
 'spacy_models': ['en', 'en-1.1.0', 'en_glove_cc_300_1m_vectors-1.0.0'],
 'textacy': '0.3.4'}
```

**Comment by bdewilde** [comment]
Hi @sixhobbits , the warning is there for good reason, and shouldn't be disabled by default. But if you don't want to see it many times (and you don't need the SMOG index anyway), you have a couple options:

You can (and should!) use the new [`TextStats()`](https://textacy.readthedocs.io/en/latest/api_reference.html#textacy.text_stats.TextStats) class and only compute the statistics you need, e.g. `TextStats(doc).flesch_kincaid_grade_level`.

The warning is generated via Python's `logging` library, so you should be able to turn off (or increase the threshold level of) logging for textacy. Something like `logging.getLogger('textacy').setLevel(logging.CRITICAL)` ought to remove these WARNING-level messages, but I'll admit that I couldn't get it to work as expected. I probably have to use a separate logger for every module, in which case I confirm that `logging.getLogger('textacy.text_stats').setLevel(logging.CRITICAL)` does indeed silence the warning. I'll add module-level loggers to my to-do list.
