### ISSUE TITLE
Listing all docs for topic

### ISSUE THREAD

**Issue by rxng** [chartbeat-labs/textacy#93]
Hi,

Currently model.top_topic_docs(doc_topic_matrix, topics=-1, top_n=-1, weights=True)

lists all docs, including weights of 0. How do we get just the documents under a specific topic (rather than all or a specific number?

R

**Comment by bdewilde** [comment]
Hi @rxng , the "topics" parameter in `TopicModel.top_topic_docs()` lets you specify the topic or topics for which to return documents. When `topics=-1` (default), _all_ topics are output; for `topics=1`, only documents for topic 1 are returned; for `topics=(1,2)`, only documents for topics 1 and 2 are included. You can also filter results to only the `top_n` documents most strongly weighted for a given topic.

It sounds like you want to filter documents to only those with some minimum topic weight. Is that correct? If so, it's relatively straightforward to specify `weights=True` then just filter out the items in the method's results where the weight is too low. For example:

```
topic_id, topic_docs = list(model.top_topic_docs(doc_topic_matrix, topics=0, weights=True))[0]
min_topic_weight = 0.2
topic_docs_filtered = [
    (doc_id, topic_weight) for doc_id, topic_weight in topic_docs
    if topic_weight >= min_topic_weight]
```

Does `min_weight` seem like a potentially useful parameter to include in the method call? If so, I can add it to my backlog.

**Comment by rxng** [comment]
Hi @bdewilde yes, sort of. Kmeans clustering just lists the most related documents for each cluster, but it seems textacy is soft clustering and only assigns weights to each doc? So some doc's may not appear anywhere and we would not know.

Weight cutoffs are useful in solving this specific problem, but another problem is deciding on an optimal cutoff point that ensures all documents appear in at least one topic. How do we ensure that docs that belong anywhere are not counted in the clustering?

Thanks

**Comment by bdewilde** [comment]
Hi @rxng , this code is performing topic modeling, not clustering. Every document receives a weight for every topic — the `doc_topic_matrix` has # docs rows and # topics columns and values for each pair — but in practice many of those weights may be ~0.

If you're looking for the single, strongest-weighted topic for each document, you should call `TopicModel.top_doc_topics(doc_topic_matrix, docs=-1, top_n=1)`.
