### ISSUE TITLE
 error: narrowing conversion 

### ISSUE THREAD

**Issue by aleksandrmelnyk** [chartbeat-labs/textacy#94]
Having error when installing through pip:
cld2/internal/cld_generated_cjk_uni_prop_80.cc:7089:1: error: narrowing conversion of ‘-9’ from ‘int’ to ‘CLD2::uint8 {aka unsigned char}’ inside { } [-Wnarrowing]

**Comment by aleksandrmelnyk** [comment]
Arch Linux 
gcc (GCC) 6.3.1 20170306

**Comment by bdewilde** [comment]
Hi @aleksandrmelnyk , installation of `cld2-cffi` has been [a long-standing difficulty](https://github.com/GregBowyer/cld2-cffi/issues/12) for some people. Could you try installing it separately, before installing `textacy`? 

```
$ CFLAGS="-Wno-narrowing" pip install cld2-cffi
$ pip install textacy[all]
```

In the next version of `textacy`, this will be an optional dependency...
