### ISSUE TITLE
Textacy Extract Example returns empty list

### ISSUE THREAD

**Issue by agsax2002** [chartbeat-labs/textacy#98]
Hi Burton or whomever is reading this. I am walking through the example code in the readme and getting weird results. I have installed everything required as far as I can tell, but unsure if the issue is with my environment or the code. This command is one of several that are not generating the same output as in the readme page.

My goal is to walk through the readme and learn how to use this library before using it on new text data. 

## Expected Behavior
From the readme file, this is what I expect to see. I have executed all the previous commands in the readme without issue.
list(textacy.extract.named_entities(
...     doc, drop_determiners=True, exclude_types='numeric'))[:10]
[Senate,
 Senate,
 American,
 New York,
 New Yorkers,
 Senate,
 Barbara Mikulski,
 Senate,
 Pennsylvania Avenue,
 Senate]

## Current Behavior
This is what I see:
list(textacy.extract.named_entities(doc, drop_determiners=True, exclude_types='numeric'))[:10]
[ ]

It's an empty list.

## Possible Solution
No idea. I reinstalled all the language models from spaCy.

## Your Environment

* `textacy` and `spacy` versions: textacy-0.3.4, spacy-0.101.0
* Python version: Python 3.5.2 :: Continuum Analytics, Inc.
* Operating system and version: OS X 10.10.5

**Comment by bdewilde** [comment]
Hey @agsax2002 , I don't know specifically why that's happening, but I see that the version of spacy you've listed is quite old. textacy requires spacy>=1.7.0,<2.0.0. Could you install an updated version — and don't forget the models — then let me know if it works as expected?

**Comment by agsax2002** [comment]
I'm looking into this and seeing why my version is so old.

**Comment by agsax2002** [comment]
in my Anaconda environment, I found that I had two versions of spacy installed. The Anaconda version was old (0.101.0), but I also had the pip version (1.8.2). I uninstalled the old version, leaving only the new  version. But now I am having issues with textacy importing "util". I think this is just an environment issue, so I will try to sort this out before moving on.

**Comment by bdewilde** [comment]
Okay. I'm not an Anaconda user, and I don't really know how it works under the hood. Let me know if/when you figure this our, if you have a new error/stacktrace for me to help debug. Good luck!

**Comment by agsax2002** [comment]
I installed spacy from anaconda.org, and this seems to solve my issue.
Website: https://anaconda.org/conda-forge/spacy
Installation code: conda install -c conda-forge spacy=1.8.2

I'm not sure why the pip version of spaCy wouldn't talk to textacy. Now that I have an updated version from Conda, my software seems happy.

I am getting results from your walkthrough, though they are different. I think this may be from using slightly different versions of spaCy or maybe your walkthrough text is outdate. I'll just move on, but fwiw, here's my output: 
list(textacy.extract.pos_regex_matches(doc, pattern))[:10]
[Mr. President,
 my voice,
 my colleagues who,
 efforts,
 this important worker health,
 safety standard,
 the remarks,
 my distinguished colleague,
 Missouri,
 many serious concerns]

corpus
Corpus(1241 docs; 858063 tokens)

print(repr(doc_term_matrix))
<1241x11690 sparse matrix of type '<class 'numpy.float64'>'
	with 214074 stored elements in Compressed Sparse Row format>

Thanks for your help. ~Best, Andrew
